### PR TITLE
608 gossiplb bugs

### LINKED ISSUE #608: Fix bugs in GossipLB
**Describe the bug**
Performance bugs

### PR DESCRIPTION
**Pull request by lifflander**
Fix bugs in GossipLB causing bad load distributions.

Fixes #608

### CODE REVIEW

File: src/vt/vrt/collection/balance/gossiplb/gossiplb.cc [hunk 1]
```diff
@@ -392,17 +392,23 @@ void GossipLB::decide() {
         // the rest of the stats framework
         auto obj_load = loadMilli(iter->second);
 
+        bool eval = Criterion(criterion_)(this_new_load_, selected_load, obj_load, avg);
```
Comment (pnstickne) [inline src/vt/vrt/collection/balance/gossiplb/gossiplb.cc]: Does `Criterion(criterion_)` const/reusable? If so, does it add any value?

Comment (PhilMiller) [reply src/vt/vrt/collection/balance/gossiplb/gossiplb.cc]: It's only used once within this entire function, so it doesn't much matter. IIRC, it should be cheap to compute anyway
