### PR TITLE
#556 restore the original coloring logic

### LINKED ISSUE #556: Color is not output by default on termination anymore (after merging #544)
**Describe the bug**
@pnstickne After merging issue #539, PR #544, the color stopped outputting by default in a normal terminal.

**To Reproduce**
1. Run any test/example.

### PR DESCRIPTION
**Pull request by lifflander**
#539, #544 caused color to *not* be output by default anymore on a my terminal (Mac). Restore the original logic (default on, not relying on `isatty`, unless `--vt_auto_color` is explicit to detect the termination type)

Fixes #556

### CODE REVIEW

File: src/vt/configs/arguments/args.cc [hunk 1]
```diff
@@ -461,7 +461,11 @@ namespace vt { namespace arguments {
   } else if (vt_color) {
     colorize_output = true;
   } else { // assume auto-color
-    colorize_output = isatty(fileno(stdout));
+    if (vt_auto_color) {
+      colorize_output = isatty(fileno(stdout));
+    } else {
+      colorize_output = not vt_no_color;
```
Comment (uhetmaniuk) [inline src/vt/configs/arguments/args.cc]: @lifflander My understanding is that CLI::excludes (b->excludes(a); b->excludes(c)) is bi-directional. So only one of the three booleans (vt_color, vt_auto_color, vt_no_color) will be true. How will the line 467 get active?

Comment (lifflander) [reply src/vt/configs/arguments/args.cc]: @uhetmaniuk That's actually what runs by default! If the user doesn't specify, `vt_auto_color` is false and VT *does not* check if the terminal is a tty. I had to do this because in many cases `isatty` returns false when it's not true.

Comment (uhetmaniuk) [reply src/vt/configs/arguments/args.cc]: @lifflander  I must be missing something... Line 59 of `args.cc` set `vt_auto_color` to `true` (by default). No?

Comment (lifflander) [reply src/vt/configs/arguments/args.cc]: No, it's false by default. Meaning that it doesn't check if the terminal is a tty by default.

```C++
/*static*/ bool        ArgConfig::vt_auto_color         = false;
```

Maybe it's different on another branch?

Comment (lifflander) [reply src/vt/configs/arguments/args.cc]: Actually, I'm sorry I've been looking at the release branch! It's indeed true by default on develop...

Comment (uhetmaniuk) [reply src/vt/configs/arguments/args.cc]: No problem! So many branches to track :)

Comment (lifflander) [reply src/vt/configs/arguments/args.cc]: he current develop fails because `isatty(fileno(stdout))` evaluates to false. So along with this maybe we should change the default to false I think.

Comment (lifflander) [reply src/vt/configs/arguments/args.cc]: Ok, so the confusing part of this is that the default value for `--vt_auto_color`, is not controlled by the static:
```C++
/*static*/ bool        ArgConfig::vt_auto_color         = true;
```
i.e., This does not actually set `vt_auto_color` to true.

Comment (uhetmaniuk) [reply src/vt/configs/arguments/args.cc]: OK

**Comment by pnstickne** [comment]
If a specific environment has issues with terminal detection, that's either 1) the environment issue or 2) the detection of coloring.

This should not dictate expected behavior or options of. Take `ls`, for example. The default to color.

File: src/vt/configs/arguments/args.cc [hunk 2]
```diff
@@ -461,7 +461,11 @@ namespace vt { namespace arguments {
   } else if (vt_color) {
     colorize_output = true;
   } else { // assume auto-color
-    colorize_output = isatty(fileno(stdout));
+    if (vt_auto_color) {
+      colorize_output = isatty(fileno(stdout));
+    } else {
+      colorize_output = true;
```
Comment (pnstickne) [inline src/vt/configs/arguments/args.cc]: With no flags, this will result in incorrect colors being emitted to pipes.

**Comment by pnstickne** [comment]
In the case of `ls`, for example, one might add an `alias ls=ls --color=true` for their specific choice without affecting the default behavior of the program itself.

**Comment by lifflander** [comment]
> @lifflander @uhetmaniuk  In the case of `ls`, for example, one might add an `alias ls=ls --color=true` for their specific local preference without affecting the default behavior of the program itself; a similar could apply to vt (eg): `alias vt=vt --vt_color` to force colors locally, regardless of the isatty check. Another option, while allowing standard-auto-coloring-expectations would be to introduce environment variables:
> 
>     `VT_COLOR=1 vt ..`

The problem is that vt is launched with `mpirun`, which may make this difficult.

**Comment by pnstickne** [comment]
For example, the `isatty` call is wrong in (at least some) MPI: https://lost-contact.mit.edu/afs/enea.it/software/doc/poe/ppe.html/d3d70mst35.html (this is an issue in the code, not with default expectations if said code was detecting correctly).

File: src/vt/configs/arguments/args.cc (hunk 2 above)
Comment (pnstickne) [reply src/vt/configs/arguments/args.cc]: In the case of `ls`, for example, one might add an `alias ls=ls --color=true`

> > @lifflander @uhetmaniuk  In the case of `ls`, for example, one might add an `alias ls=ls --color=true` for their specific local preference without affecting the default behavior of the program itself; a similar could apply to vt (eg): `alias vt=vt --vt_color` to force colors locally, regardless of the isatty check. Another option, while allowing standard-auto-coloring-expectations would be to introduce environment variables:
> > ```
> > `VT_COLOR=1 vt ..`
> > ```
> 
> The problem is that vt is launched with `mpirun`, which may make this difficult.

At least for arguments, can be pushed up at point of invocation:

     alias mpirun_vtc=mpirun vt --x

**Comment by pnstickne** [comment]
> The `isatty` call appears to be the 'issue' in (at least some) MPI: https://lost-contact.mit.edu/afs/enea.it/software/doc/poe/ppe.html/d3d70mst35.html (this is an issue in the code, not with default expectations if said code was detecting correctly). Also https://www.mail-archive.com/devel@lists.open-mpi.org/msg17764.html - so, oops :|

Really should probably just address this ..

**Comment by pnstickne** [comment]
@lifflander Let me take this and fix the terminal detection.

**Comment by pnstickne** [comment]
Color is "automatic" by default, which implies "enabled" as there is no appropriate mechanism in MPI (standard) that will answer the question correctly. Notes relating to 'terminal' have been removed and logic remains consistent.

Screen Shot 2019-11-10 at 3 18 03 PM

**Comment by pnstickne** [comment]
Or eliminate the auto-color option.
Or set to false always for auto-color 'check' and then change the default static value at the top of the file back for color-enabled.
Just minimize divergence..

**Comment by lifflander** [comment]
@pnstickne I agree--let's do away with "auto color".

**Comment by pnstickne** [comment]
Screen Shot 2019-11-12 at 8 13 50 PM

**Comment by lifflander** [comment]
@pnstickne Is this ready to merge? If so, I will test it and get it onto mainline.

**Comment by lifflander** [comment]
Rebased onto current develop
