### PR TITLE
554 demangler parsing fixes for tracing

### LINKED ISSUE #554: Trace builds of VT crash early in startup when certain callback kinds are registered (eg. reduce.cc, ~1/8 tests),
**Describe the bug**
This is related to #342, with an expanded explanation of the problem. When compiling in trace mode, the tracing component in conjunction with the registry, generates a `*.sts` file that holds all the object types and method types for reference in the projections trace.

Here's an example sts file (I've changed the extension to txt since github does not support unknown file types): [EMPIRE_PIC-NLS-release-beta3.exe.sts.txt](https://github.com/DARMA-tasking/vt/files/3811293/EMPIRE_PIC-NLS-release-beta3.exe.sts.txt)

The log files for each node refer to the sts file when tracing/logging events that occur. To see a full trace in projections, build with `-Dvt_trace_enabled=true`, run `examples/hello_world` with "--vt_trace --vt_trace_dir=testdir`. Download projections [Projections](http://charm.cs.illinois.edu/distrib/binaries/projections/projections_6.8.0.tar.gz). Open the sts file in the directory and you can look at the "Timeline" tool.

The demangler tries to parse out the object and function/functor type using compiler-specific functions for extracting. Snippet from `src/vt/utils/demangle/get_type_name.h`:

```
#if defined(__clang__)
  StaticString p = __PRETTY_FUNCTION__;
  return StaticString(p.data() + 31, p.size() - 31 - 1);

# elif defined(__GNUC__)
  StaticString p = __PRETTY_FUNCTION__;

#   if __cplusplus < 201402
    return StaticString(p.data() + 36, p.size() - 36 - 1);
#   else
    return StaticString(p.data() + 46, p.size() - 46 - 1);
#   endif

# elif defined(_MSC_VER)
  StaticString p = __FUNCSIG__;
  return StaticString(p.data() + 38, p.size() - 38 - 7);
#endif
```

This is therefore inconsistent and compiler-specific. Not only that, but the demangler does not actually parse the type but try to pull it apart with heuristics.

**To Reproduce**
1. Build VT in trace mode (`-Dvt_trace_enabled=true`)
2. Run `make test`

**Expected behavior**
Consistent types for all compilers on all tests.

**Platform (please complete the following information):**
 - All platforms

### PR DESCRIPTION
**Pull request by pnstickne**
Basic idea of unification and pushing out responsibilities. Still need to wire in the arguments.

Drafted to 554 as a pre-req.

Fixes #554

### CODE REVIEW

File: src/vt/registry/auto/auto_registry_general.h [hunk 1]
```diff
@@ -47,19 +47,93 @@
...
+template <typename ObjTypeT, typename... Args>
+struct FunctorAdapterArgs {
+  using FunctionPtrType = void (*)(Args...);
+  using ObjType = ObjTypeT;
+
+  static constexpr FunctionPtrType getFunction() {
+    return &proxyOperatorToNewInstanceReg<ObjType, Args...>;
+  }
+
+  static std::string traceGetEventType() {
```
Comment (pnstickne) [inline src/vt/registry/auto/auto_registry_general.h]: Extraction of trace information pushed as close to types as seems practical. `__PRETTY_PRINT__` are Clang/GCC/ICC(?) specific, but one might be able to get traces (FSVO) with some implementations of `type_id` (and a CXX type demangler).

The parsing code is very minimal (or rather, it's just a few dress-up helpers) and avoids some SEGV's what were occurring.

File: src/vt/registry/auto/auto_registry_general.h [hunk 2]
```diff
@@ -47,19 +47,93 @@
...
+    using TE = vt::util::demangle::TemplateExtract;
+    using DU = vt::util::demangle::DemanglerUtils;
+    auto ns = TE::getTypeName<ObjTypeT>();
+    return DU::removeSpaces(ns);
+  }
+
+  static std::string traceGetEventName() {
+    using TE = vt::util::demangle::TemplateExtract;
+    using DU = vt::util::demangle::DemanglerUtils;
+    //auto args = DU::join(",", TE::getTypeNames<Args...>());
```
Comment (pnstickne) [inline src/vt/registry/auto/auto_registry_general.h]: Recursive template fail.. TODO.

File: src/vt/registry/auto/auto_registry_general.h [hunk 3]
```diff
@@ -69,10 +143,24 @@ struct FunctorAdapterMember {
...
+  static std::string traceGetEventName() {
+    using TE = vt::util::demangle::TemplateExtract;
+    using DU = vt::util::demangle::DemanglerUtils;
+    auto barename = TE::getBarename(TE::getValueName<F,f>());
+    auto args = TE::getVoidFuncStrArgs(TE::getTypeName<F>());
+    return barename + "(" + DU::removeSpaces(args) + ")";
+  }
+
+  static size_t getNumArgs() {
+    return 0; // lies - see NumArgsTag, perhaps
```
Comment (pnstickne) [inline src/vt/registry/auto/auto_registry_general.h]: Is used/relevant for these types? :-/

File: src/vt/registry/auto/auto_registry_general_impl.h [hunk 4]
```diff
@@ -46,53 +46,52 @@
...
 
-template <typename ActFnT, typename RegT, typename InfoT, typename FnT>
+template <typename RunnableT, typename RegT, typename InfoT, typename FnT>
 AutoHandlerType registerActiveGen() {
-  return RegistrarWrapperGen<ActFnT, RegT, InfoT, FnT>().registrar.index;
+  return RegistrarWrapperGen<RunnableT, RegT, InfoT, FnT>().registrar.index;
 }
 
-template <typename ActFnT, typename RegT, typename InfoT, typename FnT>
+template <typename RunnableT, typename RegT, typename InfoT, typename FnT>
```
Comment (pnstickne) [inline src/vt/registry/auto/auto_registry_general_impl.h]: Runnable-needs-Adapter (RunnableT::AdapterType), both are separate template types.

File: src/vt/registry/auto/functor/auto_registry_functor_impl.h [hunk 5]
```diff
@@ -58,80 +57,38 @@ namespace vt { namespace auto_registry {
...
-template <typename FunctorT, typename... Args>
-static inline auto functorHandlerWrapperRval(Args&&... args) {
-  typename FunctorT::FunctorType instance;
-  return instance.operator()(std::forward<Args>(args)...);
-}
+template <typename RunnableT, typename RegT, typename InfoT, typename FnT>
+RegistrarFunctor<RunnableT, RegT, InfoT, FnT>::RegistrarFunctor() {
+  using AdapterType = typename RunnableT::AdapterType;
 
-template <typename FunctorT, typename... Args>
```
Comment (pnstickne) [inline src/vt/registry/auto/functor/auto_registry_functor_impl.h]: Now contained in the Adapter.

Comment (pnstickne) [reply src/vt/registry/auto/functor/auto_registry_functor_impl.h]: Was able to (had to?) eliminate the msg differentiation on forwarding.. not.. sure if such is required.

File: src/vt/registry/auto/auto_registry_general.h [hunk 6]
```diff
@@ -69,10 +143,24 @@ struct FunctorAdapterMember {
...
+    auto ns = TE::getNamespace(TE::getValueName<F,f>());
+    return DU::removeSpaces(ns);
+  }
+
+  static std::string traceGetEventName() {
+    using TE = vt::util::demangle::TemplateExtract;
+    using DU = vt::util::demangle::DemanglerUtils;
+    auto barename = TE::getBarename(TE::getValueName<F,f>());
+    auto args = TE::getVoidFuncStrArgs(TE::getTypeName<F>());
+    return barename + "(" + DU::removeSpaces(args) + ")";
```
Comment (pnstickne) [inline src/vt/registry/auto/auto_registry_general.h]: Should wrap all bar ".." in std::string("..") or, does even matter? Or is there a better way to handle string concat (as in, easier).

File: src/vt/registry/auto/auto_registry_general.h [hunk 7]
```diff
@@ -69,10 +143,24 @@ struct FunctorAdapterMember {
 
   static constexpr FunctionPtrType getFunction() { return f; }
 
-  template <typename... A>
-  auto operator()(A&&... a) -> decltype(auto) {
-    return f(std::forward<A>(a)...);
-   }
+  static std::string traceGetEventType() {
```
Comment (pnstickne) [inline src/vt/registry/auto/auto_registry_general.h]: Should/could be wrapped in `#if .. trace` perhaps.

File: src/vt/registry/auto/auto_registry_general.h [hunk 8]
```diff
@@ -47,19 +47,93 @@
...
+static inline auto proxyOperatorToNewInstanceReg(Args... args) {
+  T instance;
+  return instance.operator()(args...);
+}
+
+/// All Functor Adapters require:
+/// - FunctionPtrType
+/// - ObjType
+/// - getFunction
+/// - traceGetEventType
```
Comment (pnstickne) [inline src/vt/registry/auto/auto_registry_general.h]: ..for when trace is enabled.

File: src/vt/registry/auto/auto_registry_general.h [hunk 9]
```diff
@@ -47,19 +47,93 @@
...
+/// - traceGetEventName
+/// (The 'Functor' naming is a bit of a misnomer as they are not functors
+///  nor do they strictly wrap functors..)
+
+/// Adapt a type that provides operator()(..)
+/// NOTE:
+/// MULTIPLE INSTANCES of the type will be created and discarded.
+/// This cannot be used for a stateful instance.
+/// This is an implementation detail that could be reconsidered.
+template <typename ObjTypeT, typename... Args>
```
Comment (pnstickne) [inline src/vt/registry/auto/auto_registry_general.h]: Pulled from the functor header so that adapters are side x side.

Comment (pnstickne) [reply src/vt/registry/auto/auto_registry_general.h]: This adapter is used 'very infrequently' in the examples.

**Comment by pnstickne** [comment]
And, now collects `operator(Args..)` case .. GCC builds still hosed; warnings, and more importantly: I've got my lib's crossed >_<.

**Comment by pnstickne** [comment]
Tests still don't pass .. all examples run to completion good STS output.

**Comment by pnstickne** [comment]
@lifflander This is ready to go. I would merge this as it also includes the #575 issues and fixes SEGV's that occur in several examples (including 'reduce).

Only one test fails locally, and I believe that to be a test consistency issue (sometimes is it transpose_4, transpose_8, or both).

> 99% tests passed, 1 tests failed out of 681
> 
> Total Test time (real) =  89.61 sec
> 
> The following tests FAILED:
> 	132 - vt:transpose_8 (Failed)
> Errors while running CTest
> make: *** [test] Error 8

File: src/vt/registry/auto/functor/auto_registry_functor_impl.h [hunk 10]
```diff
@@ -58,80 +57,38 @@ namespace vt { namespace auto_registry {
...
-static inline auto functorHandlerWrapperReg(Args... args) {
-  typename FunctorT::FunctorType instance;
-  return instance.operator()(args...);
-}
+  RegT& reg = getAutoRegistryGen<RegT>();
+  index = reg.size(); // capture current index
```
Comment (pnstickne) [inline src/vt/registry/auto/functor/auto_registry_functor_impl.h]: Uh, how is this code compiling? What `index` is being used?

**Comment by pnstickne** [comment]
@lifflander Back-merged in 575.

File: src/vt/registry/auto/functor/auto_registry_functor_impl.h (hunk 10 above)
Comment (pnstickne) [reply src/vt/registry/auto/functor/auto_registry_functor_impl.h]: Derp.

**Comment by lifflander** [comment]
I just rebased this on latest develop and changed the target.

```
/Users/jliffla/codes/vt/virtual-transport/src/vt/utils/demangle/demangle.cc:159:9: warning: comparison of unsigned expression >= 0 is always true [-Wtautological-compare]
  if (e >= 0 && typestr[e] == ')') {
      ~ ^  ~
1 warning generated.
```

@pnstickne Can you fix this warning? I'm not sure if there is actually a bug here or if this just needs to be removed?

File: src/vt/registry/auto/auto_registry_general.h (hunk 9 above)
Comment (lifflander) [reply src/vt/registry/auto/auto_registry_general.h]: Indeed, it's an alternative interface.

File: src/vt/registry/auto/auto_registry_general.h (hunk 6 above)
Comment (lifflander) [reply src/vt/registry/auto/auto_registry_general.h]: I don't think it matters. We are not worried about speed to much in this case---otherwise we would use `std::stringstream`

File: src/vt/registry/auto/functor/auto_registry_functor_impl.h (hunk 5 above)
Comment (lifflander) [reply src/vt/registry/auto/functor/auto_registry_functor_impl.h]: Great

**Comment by pnstickne** [comment]
Oh goodness. That's a useful warning as std::nopos is the correct compare.. still used to -1 for not found. I'll get in correction.

**Comment by pnstickne** [comment]
Warning should be gone.

**Comment by pnstickne** [comment]
Super super recommend. It also means that I can run tests with tracing mode enabled 💃

**Comment by pnstickne** [comment]
Having this in whatever main WIP would be so handy to avoid "random yet predictable crashes" failures during startup of various programs.
