### PR TITLE
575 event registry bugs

### LINKED ISSUE #575: Events not found (and causing crash on trace write)
During the trace write, all events must exist. However the events (that were previously registered) are not being found.

This appears to be an issue with initialization. The original code looks like it attempts to address the issue with template initialization ordering.

### PR DESCRIPTION
**Pull request by pnstickne**
"Works better". Pre-work to make #554 easier, as in 'not going to run into these issues'.

This will be part of #554 and as it contains trace-related bugs still.

- fixed (apparent?) initialization ordering issue where events add during initialization could not be found later in certain cases (differed by example project).
- fixed cross-access of iterators
- a bunch of updates for consistency, responsibility hiding, etc.

Fixes #575

### CODE REVIEW

File: src/vt/trace/trace.cc [hunk 1]
```diff
@@ -817,15 +822,15 @@ void Trace::outputControlFile(std::ofstream& file) {
   ContainerEventSortedType sorted_event;
   ContainerEventTypeSortedType sorted_event_type;
 
-  for (auto&& elem : TraceContainersType::getEventContainer()) {
+  for (auto&& elem : *TraceContainersType::getEventContainer()) {
```
Comment (pnstickne) [inline src/vt/trace/trace.cc]: Probably a better way to do this than `*`. Copy-constructor in that case?

File: src/vt/trace/trace_containers.cc [hunk 2]
```diff
@@ -0,0 +1,54 @@
...
+// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
+// POSSIBILITY OF SUCH DAMAGE.
+//
+// Questions? Contact darma@sandia.gov
+//
+// *****************************************************************************
+//@HEADER
+*/
+
+#include "vt/config.h"
```
Comment (pnstickne) [inline src/vt/trace/trace_containers.cc]: Should remove non-necessary headers.

File: src/vt/trace/trace_containers.h [hunk 3]
```diff
@@ -70,32 +70,29 @@ using TraceContainerEventClassType = EventLookupType<TraceEntryIDType, EventClas
 
 struct Trace;
 
-// Use static template initialization pattern to deal with ordering issues with
-// auto-registry
-template <typename = void>
+// Container types are created-as-needed, which occurs during
```
Comment (pnstickne) [inline src/vt/trace/trace_containers.h]: "After making these changes, events are found in the programs that don't crash". As such, I suspect it's due to an initialization ordering issue.

File: src/vt/trace/trace_containers.h [hunk 4]
```diff
@@ -70,32 +70,29 @@ using TraceContainerEventClassType = EventLookupType<TraceEntryIDType, EventClas
...
+// intialization to avoid intiailization ordering issues.
 class TraceContainers {
  public:
-  static TraceContainerEventClassType& getEventTypeContainer(){
-    return event_type_container;
+  static TraceContainerEventClassType* getEventTypeContainer(){
+    if (not event_type_container_)
```
Comment (pnstickne) [inline src/vt/trace/trace_containers.h]: Could hide the pointers behind a wrapper, although seems legit as so.

File: src/vt/trace/trace_event.cc [hunk 5]
```diff
@@ -55,7 +55,7 @@ EventClass::EventClass(
 ) : event(in_event), hash_event(in_hash_event)
 {
   auto const& event_hash =  std::hash<std::string>{}(in_hash_event);
-  this_event_ = event_hash;
+  this_event_ = event_hash == 0 ? 1 : event_hash;
```
Comment (pnstickne) [inline src/vt/trace/trace_event.cc]: Can *technically* occur. Also future changes planned to ensure that the ID is guaranteed unique instead of probably unique. Many sides, still dice.

File: src/vt/trace/trace_registry.cc [hunk 6]
```diff
@@ -0,0 +1,120 @@
...
+#include "vt/trace/trace_event.h"
+#include "vt/trace/trace_containers.h"
+#include "vt/trace/trace_registry.h"
+
+namespace vt { namespace trace {
+
+/*static*/ TraceEntryIDType
+TraceRegistry::registerEventHashed(
+    std::string const& event_type_name, std::string const& event_name
+  ) {
```
Comment (pnstickne) [inline src/vt/trace/trace_registry.cc]: Extra space.

File: src/vt/trace/trace_registry.cc [hunk 7]
```diff
@@ -0,0 +1,120 @@
...
+  } else {
+    event_seq = event_iter->second.theEventSeq();
+  }
+
+  return new_event.theEventId();
+}
+
+/*static*/ void
+TraceRegistry::setTraceName(
+  TraceEntryIDType id, std::string const& name, std::string const& parent) {
```
Comment (pnstickne) [inline src/vt/trace/trace_registry.cc]: `)` should trail for consistency.

File: src/vt/trace/trace_registry.cc [hunk 8]
```diff
@@ -0,0 +1,120 @@
...
+      );
+      if (iter != event_types->end()) {
+        iter->second.setEventName(parent);
+      }
+    }
+  }
+#endif
+}
+
+/*static*/ bool TraceRegistry::getEventSequence(TraceEntryIDType id, TraceEntryIDType &seq) {
```
Comment (pnstickne) [inline src/vt/trace/trace_registry.cc]: Formatting..

Comment (pnstickne) [reply src/vt/trace/trace_registry.cc]: Maybe expose the event object directly.

File: src/vt/trace/trace_containers.cc [hunk 9]
```diff
@@ -0,0 +1,54 @@
...
+#include "vt/trace/trace_common.h"
+#include "vt/trace/trace_containers.h"
+
+namespace vt { namespace trace {
+
+/*static*/ TraceContainerEventClassType* TraceContainers::event_type_container_ = nullptr;
```
Comment (pnstickne) [inline src/vt/trace/trace_containers.cc]: Maybe brace-initializer. Not quite sure how this is guaranteed pre-C++17.

File: src/vt/trace/trace_containers.cc [hunk 10]
```diff
@@ -0,0 +1,54 @@
+/*
+//@HEADER
+// *****************************************************************************
+//
+//                              trace_containers.h
```
Comment (pnstickne) [inline src/vt/trace/trace_containers.cc]: Lies..

File: src/vt/trace/trace.cc [hunk 11]
```diff
@@ -629,19 +631,20 @@ void Trace::writeTracesFile() {
...
 
-    auto event_iter = TraceContainersType::getEventContainer().find(log->ep);
-
-    vtAssert(
-      log->ep == no_trace_entry_id or
-      event_iter != TraceContainersType::getEventContainer().end(),
-      "Event must exist that was logged"
-    );
+    auto* events = TraceContainersType::getEventContainer();
+    auto event_iter = events->find(log->ep);
```
Comment (pnstickne) [inline src/vt/trace/trace.cc]: Can just use `getEventSequence`..

File: src/vt/trace/trace.cc [hunk 12]
```diff
@@ -452,18 +462,19 @@ TraceEventIDType Trace::logEvent(LogPtrType log) {
 
   auto grouped_begin = [&]() -> TraceEventIDType {
     if (not open_events_.empty()) {
+      LogType* top_event = open_events_.top();
```
Comment (pnstickne) [inline src/vt/trace/trace.cc]: Could unify with following..

File: src/vt/registry/auto/auto_registry_impl.h [hunk 13]
```diff
@@ -155,28 +155,7 @@ void setHandlerTraceName(std::string const& name, std::string const& parent) {
...
-        "Event type must exist",
-        name, parent, id, type_id
-      );
-      if (iter != TraceContainersType::getEventTypeContainer().end()) {
-        iter->second.setEventName(parent);
-      }
-    }
-  }
-#endif
+  trace::TraceRegistry::setTraceName(id, name, parent);
```
Comment (pnstickne) [inline src/vt/registry/auto/auto_registry_impl.h]: Could pull up/out further.

File: src/vt/trace/trace_event.cc (hunk 5 above)
Comment (pnstickne) [reply src/vt/trace/trace_event.cc]: Actually, since the MSVC 10 issue it seems like all hashes are FNV64 or-better, so assuming size_t is 2^64..

File: src/vt/trace/trace.cc (hunk 11 above)
Comment (pnstickne) [reply src/vt/trace/trace.cc]: Done.

File: src/vt/trace/trace_containers.h (hunk 3 above)
Comment (pnstickne) [reply src/vt/trace/trace_containers.h]: (Where 'these changes' are specifically related to returning a new'ed pointer instead of a reference to a static object created during initialization somewhere..)

File: src/vt/trace/trace.cc (hunk 1 above)
Comment (pnstickne) [reply src/vt/trace/trace.cc]: Actually, "shouldn't" make a copy in this case. Seems legit.

File: src/vt/trace/trace_registry.cc [hunk 14]
```diff
@@ -0,0 +1,128 @@
...
+      if (iter != event_types->end()) {
+        iter->second.setEventName(type_name);
+      }
+    }
+  }
+#endif
+}
+
+/*static*/ bool
+TraceRegistry::getEventSequence(TraceEntryIDType id, TraceEntryIDType &seq) {
```
Comment (pnstickne) [inline src/vt/trace/trace_registry.cc]: No "0 sentinel" for TraceEntryIDType.. maybe it should be a TraceEntrySeqType split on *signed* int so < 0 is sentinel.

File: src/vt/trace/trace_containers.h (hunk 3 above)
Comment (lifflander) [reply src/vt/trace/trace_containers.h]: With your changes, is all this still happening at static init time? It must execute then for correctness, except for the user's override `setTraceName`, if the user desires to override the given name.

File: src/vt/trace/trace_containers.h [hunk 15]
```diff
@@ -50,70 +50,36 @@
...
-// Use static template initialization pattern to deal with ordering issues with
-// auto-registry
-template <typename = void>
+// Container types are created-as-needed, which occurs during
+// intialization to avoid intiailization ordering issues.
 class TraceContainers {
  public:
-  static TraceContainerEventClassType& getEventTypeContainer(){
-    return event_type_container;
+  static TraceContainerEventClassType* getEventTypeContainer(){
```
Comment (lifflander) [inline src/vt/trace/trace_containers.h]: What is the motivation of hoisting this to a pointer?

File: src/vt/trace/trace_containers.cc [hunk 16]
```diff
@@ -0,0 +1,12 @@
+#include "vt/trace/trace_common.h"
+#include "vt/trace/trace_containers.h"
+
+namespace vt { namespace trace {
+
+/*static*/ TraceContainerEventClassType*
```
Comment (lifflander) [inline src/vt/trace/trace_containers.cc]: I think you should initialize this variable to `nullptr`

File: src/vt/messaging/active.cc [hunk 17]
```diff
@@ -298,19 +298,12 @@ EventType ActiveMessenger::sendMsgSized(
     base, uninitialized_destination, msg_size, true, &deliver
   );
 
-  EventType ret = no_event;
-
   if (deliver) {
-    EventType event = no_event;
-
     sendMsgBytesWithPut(dest, base, msg_size, send_tag);
```
Comment (lifflander) [inline src/vt/messaging/active.cc]: I think there was a bug here before, or maybe the code change. I thought that `sendMsgBytesWithPut` should return an event. I think the code was refactored a long time ago not to, but this code didn't get updated.

File: src/vt/trace/trace.cc [hunk 18]
```diff
@@ -573,21 +588,11 @@ TraceEventIDType Trace::logEvent(LogPtrType log) {
...
-      return true;
-    } else if (node % ArgType::vt_trace_mod == 1) {
-      return true;
-    } else {
-      return false;
-    }
-  } else {
-    return false;
-  }
+  return ArgType::vt_trace
```
Comment (lifflander) [inline src/vt/trace/trace.cc]: Nice cleanup!

File: src/vt/trace/trace_containers.h [hunk 19]
```diff
@@ -50,70 +50,36 @@
...
+    if (not event_type_container_)
+      event_type_container_ = new TraceContainerEventClassType();
```
Comment (lifflander) [inline src/vt/trace/trace_containers.h]: I don't see any `delete` almost sure that this leaks memory. Why are you using a manually allocated object? I would steer away from this. Ideally, C++ code should never include a `new`

File: src/vt/trace/trace_containers.cc (hunk 16 above)
Comment (pnstickne) [reply src/vt/trace/trace_containers.cc]: Without the assignment it's guaranteed to be assigned all-zeros in the STATIC initialization. It's not until C++17 that assignment (in certain cases) is done during static initialization.

File: src/vt/trace/trace_containers.h (hunk 19 above)
Comment (pnstickne) [reply src/vt/trace/trace_containers.h]: Never deleted. Global statics. Used when events are written.

Comment (pnstickne) [reply src/vt/trace/trace_containers.h]: `static_lifetime_events_` (eg.)

File: src/vt/trace/trace_containers.h (hunk 15 above)
Comment (pnstickne) [reply src/vt/trace/trace_containers.h]: This could probably also be done with initialization of a non-pointer type (and separate variable capturing initialization state). Main change is it allows detection of initialization.

Comment (pnstickne) [reply src/vt/trace/trace_containers.h]: if (not event_container_intiailized_) {
       event_container_ = EventContainerType{};
       event_container_intiailized_ = true;
   }
   return event_container_;

File: src/vt/trace/trace_containers.cc (hunk 16 above)
Comment (pnstickne) [reply src/vt/trace/trace_containers.cc]: (I had it first assigning to nullptr and then removed it - a comment would probably be useful.)

File: src/vt/trace/trace_containers.h (hunk 15 above)
Comment (pnstickne) [reply src/vt/trace/trace_containers.h]: However, even then my concern was it might be *re-initialized* later on.

File: src/vt/trace/trace_containers.cc (hunk 16 above)
Comment (pnstickne) [reply src/vt/trace/trace_containers.cc]: @lifflander It looks like a `unique_ptr` would still work with the default ctor (as it is `constexpr`); don't quite know what C++ level guarantees constexpr as static non-local initialization. Would still be returned as a raw ptr, accessed from `get` to usages.

Comment (pnstickne) [reply src/vt/trace/trace_containers.cc]: - https://en.cppreference.com/w/cpp/memory/unique_ptr/unique_ptr

Comment (pnstickne) [reply src/vt/trace/trace_containers.cc]: > Constant initialization is performed after (until C++14)instead of (since C++14) zero initialization of the static and thread-local objects and before all other initialization. Only the following variables are constant initialized:

> 2) .. Static or thread-local object of class type that is initialized by a constructor call, if the constructor is constexpr ..

Comment (pnstickne) [reply src/vt/trace/trace_containers.cc]: Also then a shared_ptr: `constexpr shared_ptr() noexcept;`.

Comment (pnstickne) [reply src/vt/trace/trace_containers.cc]: Violated by unordered_map: https://en.cppreference.com/w/cpp/container/unordered_map/unordered_map

**Comment by nlslatt** [comment]
@lifflander I don't know if it's related to this PR or not (I'm using beta.4 plus this PR on Mutrino), but I'm seeing an entry method hidden by Projections because there are no tracing events associated with it, even though it should have run many times.  I'm specifically talking about Frontend::requestFields, which is called unconditionally by Backend::updateFieldSolutions (which itself does appear in the traces many times).

**Comment by lifflander** [comment]
> @lifflander I don't know if it's related to this PR or not (I'm using beta.4 plus this PR on Mutrino), but I'm seeing an entry method hidden by Projections because there are no tracing events associated with it, even though it should have run many times. I'm specifically talking about Frontend::requestFields, which is called unconditionally by Backend::updateFieldSolutions (which itself does appear in the traces many times).

Was this also happening before 575 was being used?
