### PR TITLE
#2125: Fix sprintf warnings

### LINKED ISSUE #2125: sprintf warning on macOS
**What Needs to be Done?**

When building on mac I am seeing a warning of `'sprintf' is deprecated`
It recommends using `snprintf` .

Also might be useful to enable `-Werror` in macos builds.

### PR DESCRIPTION
**Pull request by thearusable**
Closes #2125

### CODE REVIEW

**Review by JacobDomagala — APPROVED** [review]

File: src/vt/group/collective/group_info_collective.cc [hunk 1]
```diff
@@ -696,11 +696,12 @@ void InfoColl::finalize() {
...
 
     if (!vt_check_enabled(production_build)) {
-      char buf[256];
+      constexpr int max_buffer_length = 256;
+      char buf[max_buffer_length];
       buf[0] = '\0';
       int cur = 0;
       for (auto&& elm : collective_->span_children_) {
-        cur += sprintf(buf + cur, "%d,", elm);
+        cur += snprintf(buf + cur, max_buffer_length, "%d,", elm);
```
Comment (nlslatt) [inline src/vt/group/collective/group_info_collective.cc:704]: Should this use `max_buffer_length - cur` instead of `max_buffer_length` because we are potentially writing mid-buffer?

**Review by nlslatt — CHANGES_REQUESTED** [review]
Please see comment below.

File: src/vt/group/collective/group_info_collective.cc (hunk 1 above)
Comment (thearusable) [reply src/vt/group/collective/group_info_collective.cc]: Ah, Yes, You're right.

**Review by nlslatt — APPROVED** [review]
Looks good

**Review by lifflander — APPROVED** [review]
