### PR TITLE
2028 setcontext doesnt suspend correct task with threads

### LINKED ISSUE #2028: SetContext doesn't suspend correct task with threads
**Describe the bug**
When there are nested tasks, the suspended task isn't tracked properly causing an assert to fail.

### PR DESCRIPTION
**Pull request by lifflander**
Fixes #2028

### CODE REVIEW

**Review by PhilMiller — APPROVED** [review]

**Comment by PhilMiller** [comment]
Someone else should review this besides me, because Jonathan and I pair-programmed it. In particular, it would be valuable to get some assurance that someone else can understand what's going on, or get us to write the comments that enable that understanding.

**Comment by PhilMiller** [comment]
The threading test looks good. I'm glad it turned out to be so simple to set up and catch the issue

File: tests/unit/active/test_async_op_threads.cc [hunk 1]
```diff
@@ -71,7 +73,6 @@ struct MyObjGroup {
 
     // get the epoch stack and store the original size
```
Comment (nlslatt) [inline tests/unit/active/test_async_op_threads.cc:74]: Stale comment.

File: tests/unit/active/test_async_op_threads.cc [hunk 2]
```diff
@@ -104,7 +105,7 @@ struct MyObjGroup {
     theMsg()->pushEpoch(cur_ep);
     theMsg()->pushEpoch(cur_ep);
 
-    EXPECT_EQ(epoch_stack.size(), original_epoch_size + 2);
+    auto const previous_stack_size = epoch_stack.size();
```
Comment (nlslatt) [inline tests/unit/active/test_async_op_threads.cc:108]: Could you make the epoch stack size names less ambiguously self-documenting? The relationship between `previous_stack_size` and `stack_before` is not at all clear.

File: tests/unit/active/test_async_op_threads.cc [hunk 3]
```diff
@@ -91,11 +92,11 @@ struct MyObjGroup {
     }
     auto op2 = std::make_unique<messaging::AsyncOpMPI>(
       req2,
-      [this,original_epoch_size]{
+      [this]{
         done_ = true;
         // stack should be the size before running this method since we haven't
         // resumed the thread yet!
-        EXPECT_EQ(theTerm()->getEpochStack().size(), original_epoch_size - 2);
+        EXPECT_EQ(theTerm()->getEpochStack().size(), stack_before);
```
Comment (nlslatt) [inline tests/unit/active/test_async_op_threads.cc:99]: The comment above doesn't adequately explain this to me.

**Review by nlslatt — COMMENTED** [review]
It would be helpful for me to see more comments related to the transfer in/out stuff in `ThreadAction` (I have no experience with fcontext).

**Comment by PhilMiller** [comment]
Testing as a hot patch in EMPIRE also passed

File: src/vt/context/runnable_context/set_context.cc [hunk 4]
```diff
@@ -80,7 +80,13 @@ void SetContext::suspend() {
     print_ptr(this), print_ptr(prev_task_.get()), print_ptr(cur_task_.get())
   );
 
-  finish();
+  // Get the innermost task, that actually called for this thread to block
+  suspended_task_ = theContext()->getTask();
+
+  if (suspended_task_ != nullptr)
```
[the remark this answers is not in the document]
Comment (PhilMiller) [reply src/vt/context/runnable_context/set_context.cc:86]: I don't think there is any. If there's no nested task, then `suspended_task_ == this`

We can probably remove the `if` and just assert unconditionally.

**Comment by PhilMiller** [comment]
> It would be helpful for me to see more comments related to the transfer in/out stuff in `ThreadAction` (I have no experience with fcontext).

I agree. I don't entirely understand it either, and Jonathan had to work at explaining it to me.

Do you think that's essential to moving this forward?

File: src/vt/context/runnable_context/set_context.cc (hunk 4 above)
[the remark this answers is not in the document]
Comment (PhilMiller) [reply src/vt/context/runnable_context/set_context.cc:86]: What's going on here is essentially that a threaded task is always supposed to be the outermost, which corresponds to the assertion.

(writing the following mostly for my own edification / future source of documentation, rather than in answer to this particular question)

When `ThreadAction::suspend()` gets called, the `jump_fcontext` switches control to whichever of `ThreadAction::run` or `ThreadAction::resume` called into it, and the return from those goes back to the bits of runnable that call the `SetContext` methods, as well as all of the other runnable contexts bits (LB, tracing, TD, etc). At that point, it will call `SetContext::suspend` on the runnable owning the thread that it ran, rather than any nested runnable task that the thread had called into (e.g. via `invoke` or some other handler executed in-line). That runnable should always have been called directly from the vt scheduler.

Which makes me realize that we still have a hypothetical nesting problem if some code inside a threaded handler calls `runInEpoch*` or `runThroughEpoch` or anything that turns the scheduler, if there might then be suspensions of threads run within that. I think we can address that by evolving those to run the nested scheduler in a fresh thread, rather than recursively, but that's the next level of stuff to figure out and fix.

@lifflander want to write a test case for the (... in a different issue, please?)?

[the remark this answers is not in the document]
Comment (PhilMiller) [reply src/vt/context/runnable_context/set_context.cc]: Testing of the current codebase passed with that assertion being made unconditionally, at least.

File: src/vt/scheduler/thread_action.cc [hunk 5]
```diff
@@ -72,7 +72,13 @@ ThreadAction::~ThreadAction() {
 
 void ThreadAction::run() {
   ctx_ = make_fcontext_stack(stack_, runFnImpl);
+
+  auto prev_running = cur_running_;
+  cur_running_ = this;
+
```
Comment (PhilMiller) [inline src/vt/scheduler/thread_action.cc:78]:
```suggestion

// `jump_fcontext` transfers control to the fcontext thread indicated by `ctx_` that we just set up.
// Control will 'return' from `jump_fcontext` to here when that thread eventually suspends or completes
```

**Comment by nlslatt** [comment]
@lifflander @PhilMiller Is someone going to address my other review comments like deleting the stale comment?

**Comment by PhilMiller** [comment]
Should be Jonathan, as author of those tests

**Comment by lifflander** [comment]
Ok, I've finally finished with my comments and fixes and pushed.

**Review by nlslatt — APPROVED** [review]
Looks good to me
