### PR TITLE
456: Fix intel compile warnings

### LINKED ISSUE #456: Fix compiler warnings with Intel 18 (icpc) compilers
**Describe the bug**
Warnings:

```
[ 56%] Building CXX object TPL/vt/src/CMakeFiles/vt.dir/vt/messaging/pending_send.cc.o
/lscratch1/jliffla/empire-9-19/EMPIRE/TPL/vt/src/vt/registry/auto/auto_registry.cc(123): warning #1011: missing return statement at end of non-void function "vt::auto_registry::theTraceID"
  }
  ^

/lscratch1/jliffla/empire-9-19/EMPIRE/TPL/vt/src/vt/vrt/collection/balance/lb_invoke/invoke.cc(118): warning #1017: name following "template" must be a template
    proxy.get()->template startLBHandler(msg.get(), base_proxy);
                          ^
          detected during instantiation of "vt::objgroup::proxy::Proxy<LB> vt::vrt::collection::balance::LBManager::makeLB<LB>(vt::MsgSharedPtr<vt::vrt::collection::balance::StartLBMsg>) [with LB=vt::vrt::collection::lb::HierarchicalLB]" at line 150
```

**To Reproduce**
1. `ssh mutrino`
2. `source /projects/empire/mutrino/install-for-PANZER/INTEL-RELEASE-OPENMP-HSW/load_matching_env.sh`
3. Check out EMPIRE and EMPIRE-PIC
4. `cmake -DEMPIRE_ENABLE_PIC=ON -Dvt_trace_enabled=1 -Dvt_lb_enabled=1 -DCMAKE_BUILD_TYPE=release  ../EMPIRE/`
5. `make EMPIRE_PIC.exe -j40`

**Platform (please complete the following information):**
 - Mutrino
 - Intel 18 compilers, icc/icpc

### PR DESCRIPTION
**Pull request by JacobDomagala**
Fixes #456

Current warnings: 

- /vt/src/vt/scheduler/scheduler.cc(340): warning #2557: comparison between signed and unsigned operands
- /vt/src/vt/scheduler/scheduler.cc(357): warning #2557: comparison between signed and unsigned operands
- /vt/src/vt/scheduler/scheduler.cc(366): warning #2557: comparison between signed and unsigned operands
- /vt/src/vt/runtime/runtime_get.cc(168): warning #3280: declaration hides variable "vt::rt" (declared at line 72 of "/vt/src/vt/runtime/runtime_inst.h")
- /vt/examples/collection/transpose.cc(213): warning #3868: declaration hides member "SubSolveInfo::sub_comm" (declared at line 124) in same scope
- /vt/tests/unit/termination/test_term_dep_send_chain.cc(527): warning #3280: declaration hides member "vt::vrt::VrtBase::proxy_" (declared at line 73 of "/vt/src/vt/vrt/base/base.h")

### CODE REVIEW

File: tests/unit/termination/test_term_dep_send_chain.cc [hunk 1]
```diff
@@ -524,8 +524,8 @@ struct MergeCol : vt::Collection<MergeCol,vt::Index2D> {
 
   struct GhostMsg : vt::CollectionMessage<MergeCol > {
     GhostMsg() = default;
-    explicit GhostMsg(vt::CollectionProxy<MergeCol, vt::Index2D> proxy_)
-      : proxy(proxy_)
+    explicit GhostMsg(vt::CollectionProxy<MergeCol, vt::Index2D> in_proxy_)
+      : proxy(in_proxy_)
```
Comment (PhilMiller) [inline tests/unit/termination/test_term_dep_send_chain.cc:528]: Could you instead modify this class to follow the general convention of trailing underscore for member variables?

**Review by PhilMiller — APPROVED** [review]
Other than the conventions thing, this looks ready to merge. Both Intel compiler versions 18 and 19 are warning-clean for the entire vt code that CI compiles.

If we want to be thorough, it may be necessary to do builds with those compilers with a more complete feature set enabled (debugging prints, LB, tracing, mimalloc, ...)

**Comment by PhilMiller** [comment]
@lifflander Do we want to make changes to quiet warnings in libfort as well? Do we want to potentially pass changes to it upstream? Could we add in a `-w` for the build there to just silence warnings?

File: tests/unit/termination/test_term_dep_send_chain.cc (hunk 1 above)
Comment (JacobDomagala) [reply tests/unit/termination/test_term_dep_send_chain.cc]: Done

**Review by PhilMiller — APPROVED** [review]

**Comment by lifflander** [comment]
> @lifflander Do we want to make changes to quiet warnings in libfort as well? Do we want to potentially pass changes to it upstream? Could we add in a `-w` for the build there to just silence warnings?

If the warnings are easily to fix in libfort, we can fix them and pass them upstream or add `-w`.. I think either way is fine. I'm less concerned about our libraries than VT itself.

**Review by lifflander — APPROVED** [review]
Looks good to me!

**Comment by JacobDomagala** [comment]
@lifflander @PhilMiller  Ok i disabled the libfort warnings. There are still some remarks left but i guess we can ignore them.
image


 Let me know if you approve the changes.

**Review by lifflander — APPROVED** [review]
Yes, this looks good to me.
