### PR TITLE
597 migration leak

### LINKED ISSUE #597: Fix memory leaks during migration
**Describe the bug**
```
==110595== 51,888 (10,016 direct, 41,872 indirect) bytes in 86 blocks are definitely lost in loss record 31 of 36
==110595==    at 0x4C3E882: operator new(unsigned long) (vg_replace_malloc.c:334)
==110595==    by 0x440E3F: std::__detail::_Hashtable_alloc<std::allocator<std::__detail::_Hash_node<unsigned long, false> > >::_M_allocate_buckets(unsigned long) [clone .isra.2387] (in /home/jliffla/vt-auto-build/vt-lb-new-test-1.0.0/vt/v
t-build-rel-2/tests/test_term_dep_send_chain)
==110595==    by 0x48289E: std::_Hashtable<vt::vrt::collection::balance::LBCommKey, std::pair<vt::vrt::collection::balance::LBCommKey const, double>, std::allocator<std::pair<vt::vrt::collection::balance::LBCommKey const, double> >, std::
__detail::_Select1st, std::equal_to<vt::vrt::collection::balance::LBCommKey>, std::hash<vt::vrt::collection::balance::LBCommKey>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy,
 std::__detail::_Hashtable_traits<true, false, true> >::_M_rehash(unsigned long, unsigned long const&) (in /home/jliffla/vt-auto-build/vt-lb-new-test-1.0.0/vt/vt-build-rel-2/tests/test_term_dep_send_chain)
==110595==    by 0x4829C6: std::_Hashtable<vt::vrt::collection::balance::LBCommKey, std::pair<vt::vrt::collection::balance::LBCommKey const, double>, std::allocator<std::pair<vt::vrt::collection::balance::LBCommKey const, double> >, std::
__detail::_Select1st, std::equal_to<vt::vrt::collection::balance::LBCommKey>, std::hash<vt::vrt::collection::balance::LBCommKey>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy,
 std::__detail::_Hashtable_traits<true, false, true> >::_M_insert_unique_node(unsigned long, unsigned long, std::__detail::_Hash_node<std::pair<vt::vrt::collection::balance::LBCommKey const, double>, true>*, unsigned long) (in /home/jliff
la/vt-auto-build/vt-lb-new-test-1.0.0/vt/vt-build-rel-2/tests/test_term_dep_send_chain)
==110595==    by 0x4424A8: std::pair<std::__detail::_Node_iterator<std::pair<vt::vrt::collection::balance::LBCommKey const, double>, false, true>, bool> std::_Hashtable<vt::vrt::collection::balance::LBCommKey, std::pair<vt::vrt::collectio
n::balance::LBCommKey const, double>, std::allocator<std::pair<vt::vrt::collection::balance::LBCommKey const, double> >, std::__detail::_Select1st, std::equal_to<vt::vrt::collection::balance::LBCommKey>, std::hash<vt::vrt::collection::bal
ance::LBCommKey>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_emplace<std::pair<vt::vrt::collection::balance::LBCom
mKey const, double>&>(std::integral_constant<bool, true>, std::pair<vt::vrt::collection::balance::LBCommKey const, double>&) [clone .constprop.3631] (in /home/jliffla/vt-auto-build/vt-lb-new-test-1.0.0/vt/vt-build-rel-2/tests/test_term_de
p_send_chain)
==110595==    by 0x484DEC: void serdes::serialize<serdes::Unpacker, std::unordered_map<vt::vrt::collection::balance::LBCommKey, double, std::hash<vt::vrt::collection::balance::LBCommKey>, std::equal_to<vt::vrt::collection::balance::LBComm
Key>, std::allocator<std::pair<vt::vrt::collection::balance::LBCommKey const, double> > >, std::allocator<std::unordered_map<vt::vrt::collection::balance::LBCommKey, double, std::hash<vt::vrt::collection::balance::LBCommKey>, std::equal_t
o<vt::vrt::collection::balance::LBCommKey>, std::allocator<std::pair<vt::vrt::collection::balance::LBCommKey const, double> > > > >(serdes::Unpacker&, std::vector<std::unordered_map<vt::vrt::collection::balance::LBCommKey, double, std::ha
sh<vt::vrt::collection::balance::LBCommKey>, std::equal_to<vt::vrt::collection::balance::LBCommKey>, std::allocator<std::pair<vt::vrt::collection::balance::LBCommKey const, double> > >, std::allocator<std::unordered_map<vt::vrt::collectio
n::balance::LBCommKey, double, std::hash<vt::vrt::collection::balance::LBCommKey>, std::equal_to<vt::vrt::collection::balance::LBCommKey>, std::allocator<std::pair<vt::vrt::collection::balance::LBCommKey const, double> > > > >&) (in /home
/jliffla/vt-auto-build/vt-lb-new-test-1.0.0/vt/vt-build-rel-2/tests/test_term_dep_send_chain)
==110595==    by 0x484EEA: void vt::vrt::collection::Migratable<vt::tests::unit::MyCol>::serialize<serdes::Unpacker>(serdes::Unpacker&) (in /home/jliffla/vt-auto-build/vt-lb-new-test-1.0.0/vt/vt-build-rel-2/tests/test_term_dep_send_chain)
==110595==    by 0x484F50: void vt::vrt::collection::CollectionBase<vt::tests::unit::MyCol, vt::index::DenseIndexArray<int, (signed char)2> >::serialize<serdes::Unpacker>(serdes::Unpacker&) (in /home/jliffla/vt-auto-build/vt-lb-new-test-1
.0.0/vt/vt-build-rel-2/tests/test_term_dep_send_chain)
==110595==    by 0x4850D0: serdes::Dispatch<vt::vrt::collection::MigrateMsg<vt::tests::unit::MyCol, vt::index::DenseIndexArray<int, (signed char)2> > >::unpackType(char*, char*, unsigned long const&, bool) (in /home/jliffla/vt-auto-build/
vt-lb-new-test-1.0.0/vt/vt-build-rel-2/tests/test_term_dep_send_chain)
==110595==    by 0x485AB6: std::_Function_handler<void (std::tuple<void*, unsigned long>, std::function<void ()>), void vt::serialization::SerializedMessenger::serialMsgHandler<vt::vrt::collection::MigrateMsg<vt::tests::unit::MyCol, vt::i
ndex::DenseIndexArray<int, (signed char)2> > >(vt::serialization::SerializedDataMsgAny<vt::vrt::collection::MigrateMsg<vt::tests::unit::MyCol, vt::index::DenseIndexArray<int, (signed char)2> >, vt::messaging::ActiveMsg<vt::messaging::Epoc
hTagActiveEnvelope> >*)::{lambda(std::tuple<void*, unsigned long>, std::function<void ()>)#1}>::_M_invoke(std::_Any_data const&, std::tuple<void*, unsigned long>&&, std::function<void ()>&&) (in /home/jliffla/vt-auto-build/vt-lb-new-test-
1.0.0/vt/vt-build-rel-2/tests/test_term_dep_send_chain)
==110595==    by 0x4FDE10: std::_Function_handler<void (), vt::messaging::ActiveMessenger::finishPendingDataMsgAsyncRecv(vt::messaging::InProgressDataIRecv*)::{lambda()#2}>::_M_invoke(std::_Any_data const&) (in /home/jliffla/vt-auto-build/vt-lb-new-test-1.0.0/vt/vt-build-rel-2/tests/test_term_dep_send_chain)
==110595==    by 0x508C98: vt::sched::Scheduler::runNextUnit() (in /home/jliffla/vt-auto-build/vt-lb-new-test-1.0.0/vt/vt-build-rel-2/tests/test_term_dep_send_chain)
=

==110595== 351,504 (75,888 direct, 275,616 indirect) bytes in 279 blocks are definitely lost in loss record 36 of 36
==110595==    at 0x4C3E882: operator new(unsigned long) (vg_replace_malloc.c:334)
==110595==    by 0x485219: serdes::Dispatch<vt::vrt::collection::MigrateMsg<vt::tests::unit::MyCol, vt::index::DenseIndexArray<int, (signed char)2> > >::unpackType(char*, char*, unsigned long const&, bool) (in /home/jliffla/vt-auto-build/vt-lb-new-test-1.0.0/vt/vt-build-rel-2/tests/test_term_dep_send_chain)
==110595==    by 0x485AB6: std::_Function_handler<void (std::tuple<void*, unsigned long>, std::function<void ()>), void vt::serialization::SerializedMessenger::serialMsgHandler<vt::vrt::collection::MigrateMsg<vt::tests::unit::MyCol, vt::index::DenseIndexArray<int, (signed char)2> > >(vt::serialization::SerializedDataMsgAny<vt::vrt::collection::MigrateMsg<vt::tests::unit::MyCol, vt::index::DenseIndexArray<int, (signed char)2> >, vt::messaging::ActiveMsg<vt::messaging::EpochTagActiveEnvelope> >*)::{lambda(std::tuple<void*, unsigned long>, std::function<void ()>)#1}>::_M_invoke(std::_Any_data const&, std::tuple<void*, unsigned long>&&, std::function<void ()>&&) (in /home/jliffla/vt-auto-build/vt-lb-new-test-1.0.0/vt/vt-build-rel-2/tests/test_term_dep_send_chain)
==110595==    by 0x4FDE10: std::_Function_handler<void (), vt::messaging::ActiveMessenger::finishPendingDataMsgAsyncRecv(vt::messaging::InProgressDataIRecv*)::{lambda()#2}>::_M_invoke(std::_Any_data const&) (in /home/jliffla/vt-auto-build/vt-lb-new-test-1.0.0/vt/vt-build-rel-2/tests/test_term_dep_send_chain)
==110595==    by 0x508C98: vt::sched::Scheduler::runNextUnit() (in /home/jliffla/vt-auto-build/vt-lb-new-test-1.0.0/vt/vt-build-rel-2/tests/test_term_dep_send_chain)
==110595==    by 0x50959A: vt::sched::Scheduler::scheduler(bool) (in /home/jliffla/vt-auto-build/vt-lb-new-test-1.0.0/vt/vt-build-rel-2/tests/test_term_dep_send_chain)
==110595==    by 0x442CF4: vt::tests::unit::TestTermDepSendChain_test_term_dep_send_chain_Test::TestBody() (in /home/jliffla/vt-auto-build/vt-lb-new-test-1.0.0/vt/vt-build-rel-2/tests/test_term_dep_send_chain)
==110595==    by 0x4AECE9: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/jliffla/vt-auto-build/vt-lb-new-test-1.0.0/vt/vt-build-rel-2/tests/test_term_dep_send_chain)
==110595==    by 0x4A5EE6: testing::Test::Run() [clone .part.599] (in /home/jliffla/vt-auto-build/vt-lb-new-test-1.0.0/vt/vt-build-rel-2/tests/test_term_dep_send_chain)
==110595==    by 0x4A6344: testing::TestInfo::Run() [clone .part.600] (in /home/jliffla/vt-auto-build/vt-lb-new-test-1.0.0/vt/vt-build-rel-2/tests/test_term_dep_send_chain)
==110595==    by 0x4A64C4: testing::TestCase::Run() [clone .part.601] (in /home/jliffla/vt-auto-build/vt-lb-new-test-1.0.0/vt/vt-build-rel-2/tests/test_term_dep_send_chain)
==110595==    by 0x4A6F6C: testing::internal::UnitTestImpl::RunAllTests() [clone .part.618] (in /home/jliffla/vt-auto-build/vt-lb-new-test-1.0.0/vt/vt-build-rel-2/tests/test_term_dep_send_chain)
```

Debug logs with valgrind:
[run4-139584.log](https://github.com/DARMA-tasking/vt/files/3906838/run4-139584.log)
[run4-139585.log](https://github.com/DARMA-tasking/vt/files/3906839/run4-139585.log)

Release logs with valgrind:
[run12-110594.log](https://github.com/DARMA-tasking/vt/files/3906840/run12-110594.log)
[run12-110595.log](https://github.com/DARMA-tasking/vt/files/3906841/run12-110595.log)

**To Reproduce**
1. Run test on kahuna or another machine with valgrind
2. `mpirun -n 2 valgrind --log-file=run4-%p.log --leak-check=full --track-origins=yes --tool=memcheck ./tests/test_term_dep_send_chain`

### PR DESCRIPTION
**Pull request by lifflander**
Fixes #597 

Migration leak showing up in EMPIRE. During de-serialization, a copy of `ColT` was not being deallocated properly, leaking during every migration.

### CODE REVIEW

File: tests/unit/termination/test_term_dep_send_chain.cc [hunk 1]
```diff
@@ -157,7 +158,7 @@ struct MyCol : vt::Collection<MyCol,vt::Index2D> {
   void op4(ProxyMsg* msg) {
     checkExpectedStep(3);
     // fmt::print("op4: idx={}, iter={}\n", idx, iter);
-    msg->cb.send(new OpIdxMsg(idx));
+    msg->cb.send(vt::makeMessage<OpIdxMsg>(idx).get());
```
Comment (pnstickne) [inline tests/unit/termination/test_term_dep_send_chain.cc]: The result of `get()` is not obviously valid after the temporary (MsgSharedPtr) object is destroyed.. the message envelope ref will go to 0.

Comment (pnstickne) [reply tests/unit/termination/test_term_dep_send_chain.cc]: In this case, it seems like `new` is more appropriate; or to have `send` accept a MsgSharedPtr; or to otherwise have a method to 'detach'.

File: src/vt/vrt/collection/migrate/migrate_msg.h [hunk 2]
```diff
@@ -61,9 +61,15 @@ struct MigrateMsg final : ::vt::Message {
     NodeType const& in_to, HandlerType const& in_map_fn, IndexT const& in_range,
     ColT* in_elm
   ) : elm_proxy_(in_elm_proxy), from_(in_from), to_(in_to), map_fn_(in_map_fn),
-      range_(in_range), elm_(in_elm)
+      range_(in_range), owns_elm_(false), elm_(in_elm)
```
Comment (pnstickne) [inline src/vt/vrt/collection/migrate/migrate_msg.h]: Not needed in initialization list due to default value.

Comment (lifflander) [reply src/vt/vrt/collection/migrate/migrate_msg.h]: Yes, but the redundancy doesn't hurt.

Comment (pnstickne) [reply src/vt/vrt/collection/migrate/migrate_msg.h]: It doesn't help.

**Comment by PhilMiller** [comment]
Why not actually use `unique_ptr<ColT>` in `MigrateMsg`, rather than this fiddly manual ownership tracking? Either the message is carrying the object, or it's been moved out.

File: src/vt/vrt/collection/migrate/migrate_msg.h (hunk 2 above)
Comment (lifflander) [reply src/vt/vrt/collection/migrate/migrate_msg.h]: Addressed

File: tests/unit/termination/test_term_dep_send_chain.cc (hunk 1 above)
Comment (lifflander) [reply tests/unit/termination/test_term_dep_send_chain.cc]: Addressed

**Comment by lifflander** [comment]
> see about about `unique_ptr`

I've switched to `std::unique_ptr`, please re-review.

File: src/vt/vrt/collection/manager.impl.h [hunk 3]
```diff
@@ -2698,22 +2697,17 @@ MigrateStatus CollectionManager::migrateOut(
 
    using MigrateMsgType = MigrateMsg<ColT, IndexT>;
 
+   auto typed_ptr = std::unique_ptr<ColT>{static_cast<ColT*>(col_unique_ptr.release())};
    auto msg = makeSharedMessage<MigrateMsgType>(
-     proxy, this_node, dest, map_fn, range, &typed_col_ref
+     proxy, this_node, dest, map_fn, range, std::move(typed_ptr)
    );
```
Comment (PhilMiller) [inline src/vt/vrt/collection/manager.impl.h]: Just to be sure I understand correctly - is the serialization process happening inside this message constructor?  Or when the message gets serialized? I want to have a clear picture of when that happens relative to the `preMigrateOut`, `epiMigrateOut`, and `destroy` method calls.

File: src/vt/vrt/collection/migrate/migrate_msg.h [hunk 4]
```diff
@@ -86,7 +97,7 @@ struct MigrateMsg final : ::vt::Message {
   HandlerType map_fn_ = uninitialized_handler;
   IndexT range_;
 public:
-  ColT* elm_ = nullptr;
+  std::unique_ptr<ColT> elm_ = nullptr;
```
Comment (PhilMiller) [inline src/vt/vrt/collection/migrate/migrate_msg.h]: I'm being slightly obtuse here, but to confirm: this was the instance that used to leak? On the destination, the collection would copy construct from whatever this pointed to, and this would never be deleted?

**Comment by PhilMiller** [comment]
I agree that this appears to be fixing a fairly straightforward leak in a nicely straightforward way. I want to make sure I clearly understand the bits around it before approving, though.

File: src/vt/vrt/collection/manager.impl.h (hunk 3 above)
Comment (lifflander) [reply src/vt/vrt/collection/manager.impl.h]: Serialization in VT occurs when a message is sent. In this case, on the subsequent line when `theMsg()->sendMsgAuto(..)` is invoked.

Comment (lifflander) [reply src/vt/vrt/collection/manager.impl.h]: Serialization in VT occurs when a message is sent. In this case, on the subsequent line when `theMsg()->sendMsgAuto(..)` is invoked. As you probably see, I did slightly change the semantic---`epiMigrateOut` gets called now right before the send and serialization rather than after, which I think makes more sense.

File: src/vt/vrt/collection/migrate/migrate_msg.h (hunk 4 above)
Comment (lifflander) [reply src/vt/vrt/collection/migrate/migrate_msg.h]: Before this PR, the send side didn't leak, but the `new ColT` in the de-serialization on the receive side leaked. On the send side, the pointer was non-owning (a temp pointer from the send-side unique_ptr) but on the receive side it was owning.

File: src/vt/vrt/collection/manager.impl.h (hunk 3 above)
Comment (PhilMiller) [reply src/vt/vrt/collection/manager.impl.h]: Ok, so `preMigrateOut` and `epiMigrateOut` are a bit redundant. Why is even `destroy` now called before the message gets serialized and sent?

I may actually need to check how I'm using `epiMigrateOut` in EMPIRE, for some process-local cleanup of `ParticleMapContainer`

Comment (PhilMiller) [reply src/vt/vrt/collection/manager.impl.h]: Yeah, this'll break migration in EMPIRE right now, without anyplace to move the migration-specific cleanup other than the destructor. One of these functions really should be *after* serialization.

Could we just leave the sequencing of these function alone, and just fix the memory leak issue here?

Comment (nlslatt) [reply src/vt/vrt/collection/manager.impl.h]: I agree with Phil that calling `epiMigrateOut` before serialization will break migration in EMPIRE.

**Comment by lifflander** [comment]
@PhilMiller @nlslatt This is why I didn't use `std::unique_ptr` before. I can't safely keep a copy of it for after serialization. Solutions?

**Comment by lifflander** [comment]
@PhilMiller Are you ok with not using `std::unique_ptr` for this case?

**Comment by PhilMiller** [comment]
I see now why `unique_ptr` in the message ends up working poorly - after the send call, this code no longer owns the message, and so can't dereference the object pointer within it. Sorry for making you thrash around on this.

I'd be fine with a bare pointer in the message. I think the ideal in that case would be to treat the message as *never* owning the object. Once the message is deserialized, the recipient handler needs to take ownership immediately.

**Comment by lifflander** [comment]
> I see now why `unique_ptr` in the message ends up working poorly - after the send call, this code no longer owns the message, and so can't dereference the object pointer within it. Sorry for making you thrash around on this.
> 
> I'd be fine with a bare pointer in the message. I think the ideal in that case would be to treat the message as _never_ owning the object. Once the message is deserialized, the recipient handler needs to take ownership immediately.

Ok, I've reverted the last commit (`std::unique_ptr`). My changes address @pnstickne earlier comments. 

The recipient handler now does a `std::move` on the element into its unique_ptr which is stored in the `ColT` holder.

**Comment by lifflander** [comment]
> I agree the fixes the leak, but the copy or construction from the message-owned object instance is still a performance bug.

```C++
/*static*/ void MigrateHandlers::migrateInHandler(
  MigrateMsg<ColT, IndexT>* msg
) {
  auto const& from_node = msg->getFromNode();
  auto const& full_proxy = msg->getElementProxy();
  auto const& col_proxy = full_proxy.getCollectionProxy();
  auto const& elm_proxy = full_proxy.getElementProxy();
  auto const& idx = elm_proxy.getIndex();

  debug_print(
    vrt_coll, node,
    "migrateInHandler: from_node={}, idx={}\n",
    from_node, idx
  );

  auto const& map_han = msg->getMapHandler();
  auto const& range = msg->getRange();

  auto vc_elm_ptr = std::make_unique<ColT>(std::move(*msg->elm_));

  auto const& migrate_status =
    CollectionElmAttorney<ColT,IndexT>::migrateIn(
      col_proxy, idx, from_node, std::move(vc_elm_ptr), range, map_han
    );

  vtAssert(
    migrate_status == MigrateStatus::MigrateInLocal,
    "Should be valid local migration into this memory domain"
  );
}

}}} /* end namespace vt::vrt::collection */
```
