### PR TITLE
767 irecv holder fix

### LINKED ISSUE #767: Fix Irecv holder problems
**Describe the bug**
Irecvs building up in holder.

### PR DESCRIPTION
**Pull request by lifflander**
Fixes #767

### CODE REVIEW

File: src/vt/messaging/irecv_holder.h [hunk 1]
```diff
@@ -102,54 +90,44 @@ struct IRecvHolder {
...
-          progress_made = true;
-          e.valid = false;
-          holes_.push_back(i);
+      vtAssert(e.valid, "Must be valid");
+
+      int flag = 0;
+      MPI_Status stat;
+      MPI_Test(&e.req, &flag, &stat);
+
+      if (flag == 1) {
```
Comment (PhilMiller) [inline src/vt/messaging/irecv_holder.h:101]: Could you reverse this, to

```
if (flag == 0) {
  ++i;
  continue;
}
```

And then don't nest the rest of the logic?

File: src/vt/messaging/irecv_holder.h [hunk 2]
```diff
@@ -102,54 +90,44 @@ struct IRecvHolder {
...
+            trace::addUserNote(tr_note);
+          }
+        #endif
+
+        c(&e);
+        progress_made = true;
+        e.valid = false;
+
+        if (i < holder_.size() - 1) {
+          holder_[i] = std::move(holder_[holder_.size() - 1]);
```
Comment (PhilMiller) [inline src/vt/messaging/irecv_holder.h:116]: This can be written as `holder_[i] = std::move(holder_.back());`

File: src/vt/messaging/irecv_holder.h (hunk 1 above)
Comment (lifflander) [reply src/vt/messaging/irecv_holder.h]: Addessed

File: src/vt/messaging/irecv_holder.h (hunk 2 above)
Comment (lifflander) [reply src/vt/messaging/irecv_holder.h]: Fixed

File: src/vt/messaging/irecv_holder.h [hunk 3]
```diff
@@ -102,54 +90,46 @@ struct IRecvHolder {
...
+        #endif
+
+        c(&e);
+        progress_made = true;
+        e.valid = false;
+
+        if (i < holder_.size() - 1) {
+          holder_[i] = std::move(holder_.back());
+        } else {
+          ++i;
```
Comment (PhilMiller) [inline src/vt/messaging/irecv_holder.h:121]: I don't think you need the `else { ++i; }` at all - if the condition is false, then the `pop_back();` will make the `for` loop's condition false

File: src/vt/messaging/irecv_holder.h [hunk 4]
```diff
@@ -102,54 +90,46 @@ struct IRecvHolder {
...
+            trace::addUserNote(tr_note);
+          }
+        #endif
+
+        c(&e);
+        progress_made = true;
+        e.valid = false;
+
+        if (i < holder_.size() - 1) {
+          holder_[i] = std::move(holder_.back());
```
Comment (PhilMiller) [inline src/vt/messaging/irecv_holder.h:119]: And I'm prettty sure the self-assignment from an r-value reference it totally fine.

Really, I think this can just be 

```c++
holder_[i] = std::move(holder_.back());
holder_.pop_back();
```

No if or else around it, at all.

File: src/vt/messaging/irecv_holder.h [hunk 5]
```diff
@@ -102,54 +90,46 @@ struct IRecvHolder {
...
-          holes_.push_back(i);
+      vtAssert(e.valid, "Must be valid");
+
+      int flag = 0;
+      MPI_Status stat;
+      MPI_Test(&e.req, &flag, &stat);
+
+      if (flag == 0) {
+        ++i;
+        continue;
```
Comment (pnstickne) [inline src/vt/messaging/irecv_holder.h:103]: Since `continue`, might be more clear to omit the `else`.

File: src/vt/messaging/irecv_holder.h [hunk 6]
```diff
@@ -102,54 +90,46 @@ struct IRecvHolder {
...
-
-          c(&e);
-          progress_made = true;
-          e.valid = false;
-          holes_.push_back(i);
+      vtAssert(e.valid, "Must be valid");
+
+      int flag = 0;
+      MPI_Status stat;
+      MPI_Test(&e.req, &flag, &stat);
```
Comment (pnstickne) [inline src/vt/messaging/irecv_holder.h:99]: An aside: would using `MPI_Testsome` be more efficient? Or, at least delegate such as an implementation detail?

File: src/vt/messaging/irecv_holder.h (hunk 3 above)
Comment (lifflander) [reply src/vt/messaging/irecv_holder.h:121]: Fixed

File: src/vt/messaging/irecv_holder.h (hunk 4 above)
Comment (lifflander) [reply src/vt/messaging/irecv_holder.h:119]: Fixed

File: src/vt/messaging/irecv_holder.h (hunk 6 above)
Comment (lifflander) [reply src/vt/messaging/irecv_holder.h:99]: Yes, `MPI_Testany` is probably the right way to do it. However, since we still aren't storing the `MPI_Request`s contiguously in a buffer, we can't use that form. Eventually we can make this SOA to get that benefit.

File: src/vt/messaging/irecv_holder.h (hunk 5 above)
Comment (lifflander) [reply src/vt/messaging/irecv_holder.h:103]: Addressed

File: src/vt/messaging/irecv_holder.h [hunk 7]
```diff
@@ -102,54 +90,46 @@ struct IRecvHolder {
...
+      #endif
+
+      c(&e);
+      progress_made = true;
+      e.valid = false;
+
+      if (i < holder_.size() - 1) {
+        holder_[i] = std::move(holder_.back());
+      } else {
+        ++i;
```
Comment (PhilMiller) [inline src/vt/messaging/irecv_holder.h:122]: On further thought, this increment **really** can never be relevant. It only happens if we're already looking at the last element, and we're popping that last element off in the following statement. The loop ends in this case, no matter what. No need to redundantly push it off the cliff

Comment (lifflander) [reply src/vt/messaging/irecv_holder.h]: Addressed
