### PR TITLE
2472 argvcontainer leaks c string from strdup

### LINKED ISSUE #2472: ArgvContainer leaks c-string from strdup
**Describe the bug**
I don't think we need the copy here.

### PR DESCRIPTION
**Pull request by lifflander**
Fixes #2472

### CODE REVIEW

File: src/vt/collective/startup.h [hunk 1]
```diff
@@ -46,28 +46,73 @@
...
+#include <memory>
+
 namespace vt {
 
-std::unique_ptr<arguments::ArgvContainer>
-preconfigure(int& argc, char**& argv);
+/**
+ * \brief Preconfigure VT with argc/argv. This will remove all VT arguments and
+ * create a \c StartupConfig for VT that should be passed to \c
+ * initializePreconfigured. Optionally, one many specify an MPI communicator to
```
Comment (nlslatt) [inline src/vt/collective/startup.h]: Typo `many`

**Review by nlslatt — APPROVED** [review]
Looks good
