### PR TITLE
971 Fix component construction

### LINKED ISSUE #971: Fix perfect forwarding for move-only lambdas in component construction
**What Needs to be Done?**

For instance, current components constructor code does not handle passing a unique_ptr to a component constructor.

### PR DESCRIPTION
**Pull request by lifflander**
Fixes #971

### CODE REVIEW

File: src/vt/runtime/component/component_pack.cc [hunk 1]
```diff
@@ -105,9 +105,15 @@ int ComponentPack::progress() {
 
 std::list<int> ComponentPack::topoSort() {
   std::list<int> order;
+
+  registry::AutoHandlerType max_idx = 0;
+  for (auto&& r : registered_components_) {
+    max_idx = std::max(r, max_idx);
+  }
+
+  auto visited = std::make_unique<bool[]>(max_idx);
```
Comment (PhilMiller) [inline src/vt/runtime/component/component_pack.cc:114]: Are the values gotten above coming from a counter somewhere, or are they more arbitrary bit-field or address like things? If it's not from a counter, this array could be unpleasantly large

Comment (lifflander) [reply src/vt/runtime/component/component_pack.cc:114]: They are generated from a type registry is linearized and compact. However, when I started writing tests that just register and use a single test type it becomes sparse. So dense for all types ever registered (for the common case in VT that will be all components), but sparse when writing tests or just constructing a subset of the system.

**Comment by lifflander** [comment]
@cz4rs This should solve the problems that you were having with unique_ptr.
