### PR TITLE
#1999 Fix icpc/nvcc warnings seen in CDash

### LINKED ISSUE #1999: Compiler warnings from intel and nvcc
**Describe the bug**

Commit 8315da, as built on the SNL machines

Intel:
```
/.../vt/tests/unit/lb/test_lb_data_comm.cc(135): warning #177: function "vt::tests::unit::comm::<unnamed>::ReduceMsg::serialize(SerializerT &) [with SerializerT=checkpoint::Serializer]" was declared but never referenced

    void serialize(SerializerT& s) {
         ^
```

nvcc the above, and additionally:
```
/.../vt/tests/unit/collection/test_collection_group.extended.cc(57): warning: variable "vt::tests::unit::handler_executed" was set but never used
```

### PR DESCRIPTION
**Pull request by PhilMiller**
Depends on https://github.com/DARMA-tasking/magistrate/pull/266

Fixes #1999

### CODE REVIEW

**Comment by PhilMiller** [comment]
Draft status until 266 is merged, because the builds will fail

**Review by nlslatt — APPROVED** [review]

File: tests/unit/lb/test_lb_data_comm.cc [hunk 1]
```diff
@@ -762,6 +755,9 @@ TEST_F(TestLBDataComm, test_lb_data_comm_handler_to_handler_send) {
     }
   }
   EXPECT_TRUE(found);
+
+  // Suppress warnings about that method being "declared but never referenced" from Intel icpc and Nvidia nvcc
+  (void)&ReduceMsg::serialize<checkpoint::Serializer>;
```
Comment (PhilMiller) [inline tests/unit/lb/test_lb_data_comm.cc:760]: This could be addressed as part of #1316

**Comment by PhilMiller** [comment]
Success, CDash on `develop` now builds without warnings!
