### PR TITLE
2086 loosen when lbdatarestartreader is created

### LINKED ISSUE #2086: Loosen when LBDataRestartReader is created
**Describe the bug**
Right now the condition is far too specific.

```C++
bool Runtime::needLBDataRestartReader() {
  #if vt_check_enabled(lblite)
    if (arg_config_->config_.vt_lb_data) {
      auto lbNames = vrt::collection::balance::get_lb_names();
      auto mapLB = vrt::collection::balance::LBType::OfflineLB;
      if (arg_config_->config_.vt_lb_name == lbNames[mapLB]) {
        return true;
      }
    }
  #endif
  return false;
}
```

### PR DESCRIPTION
**Pull request by lifflander**
Fixes #2086

### CODE REVIEW

File: src/vt/runtime/runtime.cc [hunk 1]
```diff
@@ -385,15 +385,11 @@ bool Runtime::tryFinalize(bool const disable_sig) {
...
   #if vt_check_enabled(lblite)
-    if (arg_config_->config_.vt_lb_data) {
-      auto lbNames = vrt::collection::balance::get_lb_names();
-      auto mapLB = vrt::collection::balance::LBType::OfflineLB;
-      if (arg_config_->config_.vt_lb_name == lbNames[mapLB]) {
-        return true;
-      }
-    }
+  if (true) {
+    return arg_config_->config_.vt_lb_data_in != "";
```
Comment (nlslatt) [inline src/vt/runtime/runtime.cc:389]: I'm guessing this was meant to say `vt_lb_data_dir_in` given that you made the default value of that argument empty. If the user wants to read from the working directory, they would have to set that to `.` in order for this logic to enable the reader. Is there a reason we can't add boolean `vt_lb_data_in` like we already have a `vt_lb_data` (for outputting)?

**Review by nlslatt — CHANGES_REQUESTED** [review]

**Review by nlslatt — CHANGES_REQUESTED** [review]
The printing of the banner items for inputting LB data is conditional on the output flag, `vt_lb_data`.

**Comment by nlslatt** [comment]
> The printing of the banner items for inputting LB data is conditional on the output flag, `vt_lb_data`.

Also, `vt_lb_data_in` is missing from the serializer in `app_config.h`.

**Review by nlslatt — APPROVED** [review]
Looks good
