### PR TITLE
#610 Fix objgroup local trace bug

### LINKED ISSUE #610: Local objgroup invocations (broadcast & send) not traced
**Describe the bug**
See title

### PR DESCRIPTION
**Pull request by lifflander**
Fixes #610

This needs to be rebased when #613 gets merged.

### CODE REVIEW

File: src/vt/trace/trace_containers.cc [hunk 1]
```diff
@@ -10,11 +10,10 @@ namespace vt { namespace trace {
 // that is when auto-handler events are registered.
```
Comment (pnstickne) [inline src/vt/trace/trace_containers.cc]: Changes here follow from PR https://github.com/DARMA-tasking/vt/pull/613

**Comment by PhilMiller** [comment]
The parts that don't overlap 613 look fine.

File: src/vt/trace/trace_containers.cc (hunk 1 above)
Comment (lifflander) [reply src/vt/trace/trace_containers.cc]: #613 has been removed now
