### PR TITLE
713 Rewrite buffering code in collection manager to fix bugs

### LINKED ISSUE #713: nondeterministic assertion failure in tutorial example
**Describe the bug**
The tutorial_2 and tutorial_4 tests may nondeterministically fail.

**To Reproduce**

Tested with debug and release gcc 9.2, release clang 9
```sh
ctest -I 133,134 --repeat-until-fail 1000 --output-on-failure .
```

I have it set to 1000 repeats because the bug often does not show up.

**Expected behavior**
The test should not fail.

**Platform (please complete the following information):**
Tested with debug and release gcc 9.2, release clang 9

Ubuntu 16.04.6 LTS
Linux 4.15.0-88-generic x86_64

**Additional context**

The assert that is failing is in vrt/collection/manager.impl.h:1248:

```cpp
  } else {
    // @todo: implement this
    vtAssertExpr(0);
    return no_seq_id;
  }
```

From my understanding this branch can only be taken if the group for the collection already exists, but somehow the collection isn't fully constructed or some elements are not constructed on a node. I'll check other reduce tests to see if they have similar issues.

Stack dump (hostname and filepath removed):

```
vt: [1] ------------------------------------------------------------------------------------------------------------------------
vt: [1] ------------------------------------------- Runtime Error: System Aborting! --------------------------------------------
vt: [1] ------------------------------------------------ Fatal Error on Node 1 -------------------------------------------------
vt: [1] ------------------------------------------------------------------------------------------------------------------------
vt: [1]
vt: [1]    Assertion failed: (0)
vt: [1]                Node: 1
vt: [1]           Num Nodes: 2
vt: [1]                File: vt/src/vt/vrt/collection/manager.impl.h
vt: [1]                Line: 1248
vt: [1]            Function: reduceMsgExpr
vt: [1]                Code: 1
vt: [1]           Build SHA: a881e9a3c24c496c823a5e1b5ad0b1d88cc1d02b
vt: [1]           Build Ref: refs/heads/develop
vt: [1]         Description: heads/develop-0-ga881e9a3c2
vt: [1]            GIT Repo: clean
vt: [1]            Hostname: 
vt: [1]
vt: [1] ------------------------------------------------------------------------------------------------------------------------
vt: [1] -------------------------------------------- Dump Stack Backtrace on Node 1 --------------------------------------------
vt: [1] ------------------------------------------------------------------------------------------------------------------------
vt: [1] 0   18  0x11b53bc     vt::debug::stack::dumpStack[abi:cxx11](int) + 56
vt: [1] 1   18  0x1189a02     vt::runtime::Runtime::output(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, bool, bool, bool) + 1278
vt: [1] 2   18  0x100e160     vt::CollectiveAnyOps<(vt::runtime::eRuntimeInstance)0>::output(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, bool, bool, bool, bool) + 194
vt: [1] 3   18  0x100d6a1     vt::output(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, bool, bool, bool, bool) + 110
vt: [1] 4   18  0xdcdf50      void vt::debug::assert::assertOutExpr<void>(bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int) + 363
vt: [1] 5   18  0xde2d53      unsigned long vt::vrt::collection::CollectionManager::reduceMsgExpr<vt::tutorial::ReduceCol, vt::tutorial::ReduceMsg, &(void vt::collective::reduce::operators::ReduceCombine<void>::msgHandler<vt::tutorial::ReduceMsg, vt::collective::reduce::operators::PlusOp<int>, vt::tutorial::PrintReduceResult>(vt::tutorial::ReduceMsg*))>(vt::vrt::collection::CollectionProxy<vt::tutorial::ReduceCol, vt::tutorial::ReduceCol::IndexType> const&, vt::tutorial::ReduceMsg*, std::function<bool (vt::tutorial::ReduceCol::IndexType const&)>, unsigned long, int, short) + 2541
vt: [1] 6   18  0xde21fd      vt::vrt::collection::CollectionManager::reduceMsgExpr<vt::tutorial::ReduceCol, vt::tutorial::ReduceMsg, &(void vt::collective::reduce::operators::ReduceCombine<void>::msgHandler<vt::tutorial::ReduceMsg, vt::collective::reduce::operators::PlusOp<int>, vt::tutorial::PrintReduceResult>(vt::tutorial::ReduceMsg*))>(vt::vrt::collection::CollectionProxy<vt::tutorial::ReduceCol, vt::tutorial::ReduceCol::IndexType> const&, vt::tutorial::ReduceMsg*, std::function<bool (vt::tutorial::ReduceCol::IndexType const&)>, unsigned long, int, short)::{lambda(unsigned long)#1}::operator()(unsigned long) const + 195
vt: [1] 7   18  0xe0c601      std::_Function_handler<void (unsigned long), vt::vrt::collection::CollectionManager::reduceMsgExpr<vt::tutorial::ReduceCol, vt::tutorial::ReduceMsg, &(void vt::collective::reduce::operators::ReduceCombine<void>::msgHandler<vt::tutorial::ReduceMsg, vt::collective::reduce::operators::PlusOp<int>, vt::tutorial::PrintReduceResult>(vt::tutorial::ReduceMsg*))>(vt::vrt::collection::CollectionProxy<vt::tutorial::ReduceCol, vt::tutorial::ReduceCol::IndexType> const&, vt::tutorial::ReduceMsg*, std::function<bool (vt::tutorial::ReduceCol::IndexType const&)>, unsigned long, int, short)::{lambda(unsigned long)#1}>::_M_invoke(std::_Any_data const&, unsigned long&&) + 58
vt: [1] 8   18  0xe05ddd      std::function<void (unsigned long)>::operator()(unsigned long) const + 73
vt: [1] 9   18  0xe1e4da      void vt::vrt::collection::CollectionManager::collectionGroupFinishedHan<void>(vt::vrt::collection::CollectionGroupMsg*) + 339
vt: [1] 10  18  0xe0d34b      vt::vrt::collection::CollectionManager::createGroupCollection<vt::tutorial::ReduceCol, vt::index::DenseIndexArray<int, (signed char)1> >(unsigned long const&, bool)::{lambda(unsigned long)#1}::operator()(unsigned long) const + 595
vt: [1] 11  18  0xe4ff82      std::_Function_handler<void (unsigned long), vt::vrt::collection::CollectionManager::createGroupCollection<vt::tutorial::ReduceCol, vt::index::DenseIndexArray<int, (signed char)1> >(unsigned long const&, bool)::{lambda(unsigned long)#1}>::_M_invoke(std::_Any_data const&, unsigned long&&) + 58
vt: [1] 12  18  0xe05ddd      std::function<void (unsigned long)>::operator()(unsigned long) const + 73
vt: [1] 13  18  0x111c32d     void std::__invoke_impl<void, std::function<void (unsigned long)>&, unsigned long&>(std::__invoke_other, std::function<void (unsigned long)>&, unsigned long&) + 58
vt: [1] 14  18  0x111530d     std::__invoke_result<std::function<void (unsigned long)>&, unsigned long&>::type std::__invoke<std::function<void (unsigned long)>&, unsigned long&>(std::function<void (unsigned long)>&, unsigned long&) + 55
vt: [1] 15  18  0x1114442     void std::_Bind<std::function<void (unsigned long)> (unsigned long)>::__call<void, , 0ul>(std::tuple<>&&, std::_Index_tuple<0ul>) + 72
vt: [1] 16  18  0x1113602     void std::_Bind<std::function<void (unsigned long)> (unsigned long)>::operator()<, void>() + 36
vt: [1] 17  18  0x11129a2     std::_Function_handler<void (), std::_Bind<std::function<void (unsigned long)> (unsigned long)> >::_M_invoke(std::_Any_data const&) + 32
vt: [1] 18  18  0xdce28c      std::function<void ()>::operator()() const + 50
vt: [1] 19  18  0x11d458e     vt::group::InfoColl::newTree(short const&) + 912
vt: [1] 20  18  0x11d0bfa     ./tutorial() [0x11d0bfa] + 0
vt: [1] 21  18  0x11d645a     ./tutorial() [0x11d645a] + 0
vt: [1] 22  18  0x11dc00f     std::function<void (vt::messaging::MsgSharedPtr<vt::group::GroupMsg<vt::messaging::ActiveMsg<vt::messaging::EpochTagActiveEnvelope> > >)>::operator()(vt::messaging::MsgSharedPtr<vt::group::GroupMsg<vt::messaging::ActiveMsg<vt::messaging::EpochTagActiveEnvelope> > >) const + 73
vt: [1] 23  18  0x11da035     vt::group::GroupManagerT<vt::messaging::MsgSharedPtr<vt::group::GroupMsg<vt::messaging::ActiveMsg<vt::messaging::EpochTagActiveEnvelope> > > >::triggerContinuationT(unsigned long const&, vt::messaging::MsgSharedPtr<vt::group::GroupMsg<vt::messaging::ActiveMsg<vt::messaging::EpochTagActiveEnvelope> > >) + 371
vt: [1] 24  18  0x11d38cf     vt::group::InfoColl::tree(vt::group::GroupMsg<vt::messaging::ActiveMsg<vt::messaging::EpochTagActiveEnvelope> >*) + 473
vt: [1] 25  18  0x11d509c     vt::group::InfoColl::newTreeHan(vt::group::GroupMsg<vt::messaging::ActiveMsg<vt::messaging::EpochTagActiveEnvelope> >*) + 24
vt: [1] 26  18  0xde93b4      vt::runnable::Runnable<vt::messaging::ActiveMsg<vt::messaging::ActiveEnvelope> >::run(long, void (*)(vt::messaging::BaseMsg*), vt::messaging::ActiveMsg<vt::messaging::ActiveEnvelope>*, short, int) + 764
vt: [1] 27  18  0x1121060     vt::messaging::ActiveMessenger::deliverActiveMsg(vt::messaging::MsgSharedPtr<vt::messaging::ActiveMsg<vt::messaging::ActiveEnvelope> > const&, short const&, bool) + 1186
vt: [1] 28  18  0x1120bad     vt::messaging::ActiveMessenger::processActiveMsg(vt::messaging::MsgSharedPtr<vt::messaging::ActiveMsg<vt::messaging::ActiveEnvelope> > const&, short const&, int const&, bool) + 273
vt: [1] 29  18  0x11207f2     ./tutorial() [0x11207f2] + 0
vt: [1] 30  18  0x11226be     ./tutorial() [0x11226be] + 0
vt: [1] 31  18  0xdce28c      std::function<void ()>::operator()() const + 50
vt: [1] 32  18  0x11783ba     vt::sched::PriorityUnit::execute() + 290
vt: [1] 33  18  0x1178294     vt::sched::PriorityUnit::operator()() + 24
vt: [1] 34  18  0x1176c88     vt::sched::Scheduler::runNextUnit() + 78
vt: [1] 35  18  0x11770ff     vt::sched::Scheduler::scheduler(bool) + 413
vt: [1] 36  18  0x1177991     vt::runScheduler() + 22
vt: [1] 37  18  0xdc2b33      main + 334
vt: [1] 38  18  0x7fecd03fd830 __libc_start_main + 240
vt: [1] 39  18  0xdbfb29      _start + 41
```

### PR DESCRIPTION
**Pull request by lifflander**
Fixes #713 

Fixes a non-deterministic bug in running the tutorial with group creation racing with other setup processes. 

Rewrite the collection buffering code to be more consistent

This fixes the bug after running the `tutorial` thousands of times without failure with these changes.

### CODE REVIEW

**Comment by PhilMiller** [comment]
In your testing, how reliably were you able to reproduce the tutorial bug *before* this change?

File: src/vt/vrt/collection/manager.h [hunk 1]
```diff
@@ -864,10 +868,140 @@ struct CollectionManager {
...
+
+  /**
+   * \brief Add to the current buffer-release state of a proxy
+   *
+   * \param[in] proxy the proxy of the collection
+   * \param[in] release the state to | into the bits
+   */
+  void addToState(VirtualProxyType proxy, BufferReleaseEnum release) {
+    proxy_state_[proxy] =
+      static_cast<BufferReleaseEnum>(proxy_state_[proxy] | release);
```
Comment (PhilMiller) [inline src/vt/vrt/collection/manager.h:904]: Why is this cast here? Is some compiler unhappy with assigning from the result of the arithmetic?

Comment (lifflander) [reply src/vt/vrt/collection/manager.h:904]: Yes, gcc complains without the cast.

**Comment by lifflander** [comment]
> In your testing, how reliably were you able to reproduce the tutorial bug _before_ this change?

Very reliably. With 1000 iterations, it always broke. With the fix, I ran 20,000 without it breaking.

File: src/vt/vrt/collection/manager.h [hunk 2]
```diff
@@ -864,10 +868,140 @@ struct CollectionManager {
...
+  }
+
+  /**
+   * \brief Remove from the current buffer-release state of a proxy
+   *
+   * \param[in] proxy the proxy of the collection
+   * \param[in] release the state to remove from the bits
+   */
+  void removeFromState(VirtualProxyType proxy, BufferReleaseEnum release) {
```
Comment (PhilMiller) [inline src/vt/vrt/collection/manager.h:913]: This doesn't seem to ever be called, which is good, because I don't see when it ever *would* be called. The release states seem to be strictly monotonic. Can you remove this function?

File: src/vt/vrt/collection/manager.h [hunk 3]
```diff
@@ -864,10 +868,140 @@ struct CollectionManager {
...
+    return iter != proxy_state_.end() ? iter->second : BufferReleaseEnum::Unreleased;
+  }
+
+  /**
+   * \brief Get ready bits or'ed with the required release bits
+   *
+   * \param[in] proxy the proxy of the collection
+   * \param[in] release the bits to check
+   *
+   * \return the current state | release
```
Comment (PhilMiller) [inline src/vt/vrt/collection/manager.h:936]: These comments are wrong, since you're ANDing, not ORing

File: src/vt/vrt/collection/manager.h [hunk 4]
```diff
@@ -864,10 +868,140 @@ struct CollectionManager {
...
+   */
+  BufferReleaseEnum getReadyBits(
+    VirtualProxyType proxy, BufferReleaseEnum release
+  );
+
+  /**
+   * \brief Check if the collection is ready given the release bits
```
Comment (PhilMiller) [inline src/vt/vrt/collection/manager.h:943]: Higher-level semantic descriptions would be much more helpful here - 
"Check if the collection is past the stages of setup requested in release"

File: src/vt/vrt/collection/manager.impl.h [hunk 5]
```diff
@@ -3249,6 +3006,101 @@ IndexT CollectionManager::getRange(VirtualProxyType proxy) {
...
+  return messaging::PendingSend{nullptr};
+}
+
+template <typename ColT>
+messaging::PendingSend CollectionManager::bufferOpOrExecute(
+  VirtualProxyType proxy, BufferTypeEnum type, BufferReleaseEnum release,
+  EpochType epoch, ActionPendingType action
+) {
+  if (checkReady(proxy, release)) {
+    return action();
```
Comment (PhilMiller) [inline src/vt/vrt/collection/manager.impl.h:3056]: The handling of `epoch` is inconsistent between this case and the buffered case - `epoch` should be pushed and popped here, I think

File: src/vt/vrt/collection/manager.h (hunk 2 above)
Comment (lifflander) [reply src/vt/vrt/collection/manager.h:913]: I can remove it. However, there is a slight edge case when state can be removed... the group can become "unready" after LB when the current group is invalided (an element might have migrated to a new node that didn't previously have an element). Right now, this case is not properly handled.

File: src/vt/vrt/collection/manager.impl.h [hunk 6]
```diff
@@ -2552,116 +2343,82 @@ void CollectionManager::insert(
...
+      if (insert_node == this_node) {
+        auto const& num_elms = max_idx.getSize();
+        std::tuple<> tup;
 
-    if (insert_node == this_node) {
-      auto const& num_elms = max_idx.getSize();
-      std::tuple<> tup;
+        // Set the current context index to `idx`, enabled the user to query the
+        // index during the constructor
+        IdxContextHolder::set(&cur_idx,untyped_proxy);
```
Comment (PhilMiller) [inline src/vt/vrt/collection/manager.impl.h:2381]: Does the context setting need to be a push/pop kind of arrangement, so that things don't break if collection construction is called from another collection?

Comment (PhilMiller) [reply src/vt/vrt/collection/manager.impl.h:2381]: Not a change from the current logic, but an important consideration nonetheless

Comment (lifflander) [reply src/vt/vrt/collection/manager.impl.h:2381]: That's a great point. I hadn't considered that case, but it's definitely possible to construct a collection from within a constructor of another collection.

File: src/vt/vrt/collection/manager.h (hunk 2 above)
Comment (PhilMiller) [reply src/vt/vrt/collection/manager.h:913]: I don't think that should ever be allowed to happen as described. If it can, well, that sounds like an unpleasant bug to be fixed.

**Comment by PhilMiller** [comment]
I think this is generally fine, other than the epoch inconsistency. This is a big, intricate change, but probably one that's necessary.

File: src/vt/vrt/collection/manager.impl.h (hunk 6 above)
Comment (lifflander) [reply src/vt/vrt/collection/manager.impl.h:2381]: https://github.com/DARMA-tasking/vt/issues/758

**Comment by PhilMiller** [comment]
Maybe for 1.0 we can add suitable additional synchronization in the tutorial to prevent the race condition?

File: src/vt/vrt/collection/manager.h (hunk 2 above)
Comment (lifflander) [reply src/vt/vrt/collection/manager.h:913]: Do you think that after LB, we should hold up broadcasts/reductions until the new group is fully formed? If not, we need to buffer until that new group is created.

Comment (PhilMiller) [reply src/vt/vrt/collection/manager.h:913]: I'm not sure. In a sense, I think it would be reasonable, especially for our sanity, to not run *anything* on a just-migrated collected until everything is settled back in place. Anything laxer than that, and you're probably just chasing a full-on 'anytime migration' implementation.

File: src/vt/vrt/collection/manager.impl.h (hunk 5 above)
Comment (lifflander) [reply src/vt/vrt/collection/manager.impl.h:3056]: The code is consistent with the state before I made these changes. However, you are correct that there is an inconsistency across these cases. I think that pushing the epoch is correct/appropriate here---and there might actually be a latent bug in the code.

**Comment by lifflander** [comment]
> Maybe for 1.0 we can add suitable additional synchronization in the tutorial to prevent the race condition?

That sounds reasonable to me. A simple broadcast preceding the reduce should suffice.

File: src/vt/vrt/collection/manager.h (hunk 2 above)
Comment (lifflander) [reply src/vt/vrt/collection/manager.h:913]: Removed.

File: src/vt/vrt/collection/manager.h (hunk 4 above)
Comment (lifflander) [reply src/vt/vrt/collection/manager.h:943]: Fixed

File: src/vt/vrt/collection/manager.h (hunk 3 above)
Comment (lifflander) [reply src/vt/vrt/collection/manager.h:936]: Fixed

File: src/vt/vrt/collection/manager.impl.h (hunk 5 above)
Comment (lifflander) [reply src/vt/vrt/collection/manager.impl.h:3056]: Fixed

**Comment by lifflander** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones removed
==============
+ src/vt/vrt/collection/manager.impl.h  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/lifflander/vt/pullRequest?prid=5329531&bid=17443676)

**Comment by lifflander** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones removed
==============
+ src/vt/vrt/collection/manager.impl.h  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/lifflander/vt/pullRequest?prid=5329531&bid=17443676)
