### PR TITLE
#1069 runtime - don't re-initialize MPI in interop mode

### LINKED ISSUE #1069: Argument parsing error unconditionally triggers MPI_Init
**Describe the bug**
When an invalid command-line argument is passed to vt, it calls `MPI_Init` (`src/vt/runtime/runtime.cc:153`) in the process of handling the error.  This is problematic when vt is used within EMPIRE because MPI was already initialized.

**To Reproduce**
1. Call MPI_Init in your driver before initializing vt
2. Pass an invalid command-line argument to your executable

**Expected behavior**
If MPI was already initialized, it should use the existing communicator.

### PR DESCRIPTION
**Pull request by pnstickne**
Don't crash processes by attempting to improperly call MPI_Init again.

Will still terminate a process, with diagnostic message, when there are invalid VT args. Invalid args are limited to those in the form `--vt_bad`.

Also moved any MPI_Init (when not interop) into the Runtime class itself, for parity with MPI_Finalize, full reliance on MPI_Init eating its own arguments, and some future update work.

Minor breaking: `--vt_mpi_args` is redundant and no longer supported.

fixes #1069

### CODE REVIEW

File: src/vt/runtime/runtime.cc [hunk 1]
```diff
@@ -145,13 +145,17 @@ Runtime::Runtime(
...
-    MPI_Comm_rank(comm, &rank);
+    // To better honor MPI, force an MPI_Init then MPI_Abort as relevant.
+    MPI_Comm comm = communicator_;
+
+    if (not is_interop_) {
+      MPI_Init(NULL, NULL);
+    }
+
+    int rank = 0;
+    if (comm not_eq MPI_COMM_NULL) {
```
Comment (pnstickne) [inline src/vt/runtime/runtime.cc:156]: Having MPI_COMM_NULL passed in should probably be an error in it's own right..

File: src/vt/runtime/runtime.cc [hunk 2]
```diff
@@ -165,7 +169,11 @@ Runtime::Runtime(
           << std::flush;
     }
 
-    MPI_Abort(comm, exit_code);
+    // Even in interop mode, still abort MPI.
+    if (comm not_eq MPI_COMM_NULL) {
+      MPI_Abort(comm, exit_code);
+    }
+
     std::_Exit(exit_code); // no return
```
Comment (pnstickne) [inline src/vt/runtime/runtime.cc:177]: Still terminates on invalid args -- albeit not with a random MPI failure.

File: src/vt/runtime/runtime.cc [hunk 3]
```diff
@@ -439,15 +441,14 @@ bool Runtime::finalize(bool const force_now, bool const disable_sig) {
       printShutdownBanner(num_units, coll_epochs);
     }
 
-    finalizeMPI();
```
Comment (pnstickne) [inline src/vt/runtime/runtime.cc:442]: MPI is initialized in constructor, finalized in destructor (if not under interop). Previously the MPI_Init was buried in the context constructor which was only called on the Runtime initialize.

Likewise, communicator is duplicated/created in the context constructor and free'd in the context destructor.

File: src/vt/collective/collective_ops.cc [hunk 4]
```diff
@@ -63,9 +63,11 @@ RuntimePtrType CollectiveAnyOps<instance>::initialize(
   using vt::runtime::Runtime;
   using vt::runtime::eRuntimeInstance;
 
+  MPI_Comm resolved_comm = comm not_eq nullptr ? *comm : MPI_COMM_WORLD;
```
Comment (pnstickne) [inline src/vt/collective/collective_ops.cc:66]: vt::initialize, CollectiveOps, maintains external signature.. Runtime ctor only deals with a non-ptr MPI_Comm.

**Comment by lifflander** [comment]
Is this preempted by #1093?

**Comment by pnstickne** [comment]
> Is this preempted by #1093?

I was hoping to get this merged, closing the story (focused on making VT not crash with invalid args in interop..), then follow with the other story/PR.

File: src/vt/runtime/runtime.cc [hunk 5]
```diff
@@ -127,30 +125,28 @@ Runtime::Runtime(
...
 
-  // MPI_Init 'should' be called first on the original arguments,
-  // with the justification that in some environments in addition to removing
-  // special MPI arguments, it can actually ADD arguments not from argv.
-  // That is not done here and doing so moves up parts of 'initialize' logic.
+  // Always initialize MPI first, before handling arguments.
+  // This also allows MPI a first-stab at dealing with arguments.
+  if (not is_interop_) {
+    MPI_Init(&argc, &argv);
+  }
```
Comment (PhilMiller) [inline src/vt/runtime/runtime.cc:138]: Should this carry an 
```
else { 
int flag;
MPI_Initialized(&flag);
vtAbortIf(flag == 0);
}
```

Comment (PhilMiller) [reply src/vt/runtime/runtime.cc:138]: Actually, should we also test and abort on MPI being initialized in the interop case? So put the flag and test outside the `if`, and then pick the sense of the abort depending on which case we're in?

Comment (lifflander) [reply src/vt/runtime/runtime.cc:138]: Ah, that's a good point. @pnstickne What do you think about adding this logic? I think it could be useful to detect that error.

**Review by lifflander — APPROVED** [review]

**Comment by lifflander** [comment]
This looks great to me. I think @PhilMiller has a point that we might want to add some a check for when is either not initialized and should be (and vice versa).

File: src/vt/runtime/runtime.cc (hunk 5 above)
Comment (pnstickne) [reply src/vt/runtime/runtime.cc:148]: I think it's a good idea. Changes in. It tests in both cases and should emit a "useful" message.

File: src/vt/context/context.cc [hunk 6]
```diff
@@ -56,47 +56,32 @@
...
-  } else {
-    communicator_ = MPI_COMM_WORLD;
-  }
+  is_comm_world_ = comm == MPI_COMM_WORLD;
 
   if (is_interop) {
-    MPI_Comm vt_comm;
-    MPI_Comm_dup(communicator_, &vt_comm);
-    communicator_ = vt_comm;
+    MPI_Comm_dup(comm, &comm);
```
Comment (PhilMiller) [inline src/vt/context/context.cc:69]: As a matter of good MPI practice, we should *always* duplicate the supplied comm.

For clarity, if made ubiquitously, this call can thus be rewritten `MPI_Comm_dup(comm, &communicator_)` and the assignment below deleted.

Comment (PhilMiller) [reply src/vt/context/context.cc:69]: At that point, the `is_interop` argument isn't relevant, and can be dropped from this constructor.

**Review by PhilMiller — APPROVED** [review]

File: src/vt/context/context.cc (hunk 6 above)
Comment (PhilMiller) [reply src/vt/context/context.cc:69]: I see that's handled in #1093.
