### PR TITLE
760 Tutorial: work around bug in collection buffering

### LINKED ISSUE #760: Work around for tutorial breakage due to reduction race
**Describe the bug**
There is a proper fix #757 for the reduction race described in #713, which is too heavy to go on the release branch. So this issue is for a temporary work around for the bug described in #713.

### PR DESCRIPTION
**Pull request by lifflander**
Fixes #760

### CODE REVIEW

File: tutorial/tutorial_2b.h [hunk 1]
```diff
@@ -113,13 +113,21 @@ static inline void collectionReduce() {
...
+
+  // Construct the collection collectively. By default, the elements will be
+  // block mapped to the nodes
+  auto proxy = theCollection()->constructCollective<ReduceCol>(
+    range, [](vt::Index1D idx){
+      return std::make_unique<ReduceCol>();
+    }
+  );
 
+  // Barrier to wait for all nodes to construct the collection
```
Comment (PhilMiller) [inline tutorial/tutorial_2b.h:127]: Is having made the `constructCollective` call enough, or is there something that needs to be completed afterward?

Comment (PhilMiller) [reply tutorial/tutorial_2b.h:127]: Assuming that's actually fine, this looks good to me.

Comment (lifflander) [reply tutorial/tutorial_2b.h:127]: Collective construction is enough. Currently it waits for the group to be ready correctly but not for construction. This ensures that all nodes have constructed and know about the collection.
