### PR TITLE
#611 Move statics for trace to function to fix bug w/clang 3.9

### LINKED ISSUE #611: Fix Clang 3.9 initialization bug with event containers
Clang 3.9 does not work with tracing, full stop.
There may be an issue with the unique_ptr not being correctly constant-initialized.

### PR DESCRIPTION
**Pull request by lifflander**
Fixes #611

### CODE REVIEW

File: src/vt/trace/trace_containers.cc [hunk 1]
```diff
@@ -10,11 +10,10 @@ namespace vt { namespace trace {
 // that is when auto-handler events are registered.
 // Using a constexpr constructor / initializer list is also relevant.
 // - https://en.cppreference.com/w/cpp/language/constant_initialization
-static std::unique_ptr<TraceContainerEventClassType> event_type_container_{};
-static std::unique_ptr<TraceContainerEventType> event_container_{};
 
 /*static*/ TraceContainerEventClassType*
 TraceContainers::getEventTypeContainer(){
+  static std::unique_ptr<TraceContainerEventClassType> event_type_container_ = nullptr;
```
Comment (pnstickne) [inline src/vt/trace/trace_containers.cc]: Does this would with the *other suggestions* while leaving in place?

While I can see Clang having an issue with one form, if it has an issue with all 3, then it is *horribly horrible wrong*.

Comment (lifflander) [reply src/vt/trace/trace_containers.cc]: No, I tried all the other suggestions. None of them work.

Comment (pnstickne) [reply src/vt/trace/trace_containers.cc]: Here are the explicit forms again:

      // default const-expression ctor
      static std::unique_ptr<TraceContainerEventClassType> event_type_container_; 
      // initialization list of single nullptr (const-expr) to const-expr ctor
      static std::unique_ptr<TraceContainerEventClassType> event_type_container_{nullptr};
      // should be same as above per braces-or-equals
      static std::unique_ptr<TraceContainerEventClassType> event_type_container_ = nullptr;
      // this is the form that Clang 3.9 does not work with. This should be a value-assignment,
      // although it *differs* from the other 3 above and might be the *explicit case to avoid*
      // regardless of the definition occurring in a function body.
      static std::unique_ptr<TraceContainerEventClassType> event_type_container_{};

Comment (lifflander) [reply src/vt/trace/trace_containers.cc]: All three of those other options failed.

Comment (pnstickne) [reply src/vt/trace/trace_containers.cc]: :|

Comment (pnstickne) [reply src/vt/trace/trace_containers.cc]: Okay, something seems super seriously wrong. Although that seems *too major* ..

Comment (pnstickne) [reply src/vt/trace/trace_containers.cc]: Maybe: https://bugs.llvm.org/show_bug.cgi?id=19491 (limited to OS X?); links are broken.

Comment (pnstickne) [reply src/vt/trace/trace_containers.cc]: Please add comments at the declarations inside the functions it is a Clang 3.9 work-about and must remain even though constant-initialization is well-defined in C++14 :|

I'll do it when I get home later if left alone..

File: src/vt/trace/trace_containers.cc [hunk 2]
```diff
@@ -23,6 +20,11 @@ TraceContainers::getEventTypeContainer(){
 
 /*static*/ TraceContainerEventType*
 TraceContainers::getEventContainer(){
+  // n.b. Container MUST be constant-initialized as this function is used
```
Comment (pnstickne) [inline src/vt/trace/trace_containers.cc]: Technically the comment not quite correct as it's not a requirement that it's constant-initialized in context (a C++ compiler *may* choose do so) as long as it's initialized-before-use..

File: src/vt/trace/trace_containers.cc (hunk 1 above)
Comment (PhilMiller) [reply src/vt/trace/trace_containers.cc]: Could we get a link to the Clang bug that's forcing this in the comment? Is 19491 actually the culprit?
