### PR TITLE
#2147: fix incorrect order of parameters for call to beginProcessing

### LINKED ISSUE #2147: invalid trace timings
**Describe the bug**
Projections will complain about corrupted or invalid trace files, or that the time of a handler cannot fit into an integer. Occasionally, I see large negative numbers in the latency of a handler in the trace.

This makes me think that there may be some uninitialized values in the trace.

This bug seems to be introduced by #1998 as I have bisected and versions of VT from before that was merged work correctly.

### PR DESCRIPTION
**Pull request by nmm0**
Closes #2147

I'm going to see if it is possible to add some tests, since we don't have any trace tests.

### CODE REVIEW

File: src/vt/trace/trace.cc [hunk 1]
```diff
@@ -359,7 +359,7 @@ TraceProcessingTag Trace::beginProcessing(
   );
 
   if (theConfig()->vt_trace_memory_usage) {
-    addMemoryEvent(theMemUsage()->getFirstUsage());
+    addMemoryEvent(theMemUsage()->getFirstUsage(), time);
```
Comment (nmm0) [inline src/vt/trace/trace.cc:362]: I added this so that the recorded events would be consistent (otherwise it uses the current time)

File: src/vt/trace/trace.cc [hunk 2]
```diff
@@ -404,7 +404,7 @@ void Trace::endProcessing(
...
```
Comment (nmm0) [inline src/vt/trace/trace.cc:407]: Same as above

File: src/vt/trace/trace_lite.h [hunk 3]
```diff
@@ -252,6 +252,24 @@ struct TraceLite  {
...
+
+  /**
+   * @brief Get the last recorded trace event
+   *
+   * @return the last recorded trace event
+   */
+  const LogType* getLastTraceEvent() const noexcept {
+    return traces_.empty() ? nullptr : &traces_.back();
+  }
+
```
Comment (nmm0) [inline src/vt/trace/trace_lite.h:272]: These functions are mostly used for testing but might be useful in other circumstances

File: src/vt/trace/trace_lite.h [hunk 4]
```diff
@@ -349,7 +367,7 @@ struct TraceLite  {
    *
    * \return computed bytes used for tracing (lower bound)
    */
-  std::size_t getTracesSize() const {
+  std::size_t getTracesSize() const noexcept {
```
Comment (nmm0) [inline src/vt/trace/trace_lite.h:370]: I driveby-changed this to noexcept because it should be

File: tests/unit/trace/test_runnable_context_trace.cc [hunk 5]
```diff
@@ -0,0 +1,99 @@
...
+  if (!theTrace()->checkDynamicRuntimeEnabled())
+    GTEST_SKIP() << "trace tests require --vt_trace to be set";
+
+  auto msg = makeMessage< TraceMsg >();
+
+  auto handler = auto_registry::makeAutoHandler< TraceMsg, handler_func >();
+
+  HandlerManager::setHandlerTrace(handler, true);
+
+  // Give some nonesense parameters but Trace shouldn't touch them
```
Comment (PhilMiller) [inline tests/unit/trace/test_runnable_context_trace.cc:71]:
```suggestion
  // Give some nonsense parameters but Trace shouldn't touch them
```

File: tests/unit/trace/test_runnable_context_trace.cc [hunk 6]
```diff
@@ -0,0 +1,99 @@
...
+  last_trace = theTrace()->getLastTraceEvent();
+  EXPECT_NE(last_trace, nullptr);
+  // Counterintuitive, but we restart the open event as the last action
+  EXPECT_EQ(last_trace->type, trace::eTraceConstants::BeginProcessing);
+  EXPECT_EQ(last_trace->time, TimeType{7}); // Time should still match though
+}
+
+}}} // end namespace vt::tests::unit
+
+#endif // vt_check_enabled(trace_enabled)
```
Comment (PhilMiller) [inline tests/unit/trace/test_runnable_context_trace.cc:99]: EOF newline, so Git doesn't complain, please

**Comment by PhilMiller** [comment]
Should the PR description be made a bit more comprehensive?

**Comment by PhilMiller** [comment]
Trivial remarks aside, this looks good to me.

**Review by lifflander — APPROVED** [review]

**Review by JacobDomagala — APPROVED** [review]

**Review by nlslatt — APPROVED** [review]
