### PR TITLE
#631 trace system events

### LINKED ISSUE #631: Traces are hard to understand with system level handlers
**Describe the bug**

For every message application code sends, the resulting traces of the corresponding handler will show several events, logically nested but actually broken up by the unstacking code in the trace writer. This makes application performance analysis difficult, since none of those handlers are things the user explicitly called for, and computed message receive counts are a variable multiple of send counts.

**To Reproduce**

Run an application sending messages to handlers that are methods of process, objgroup, or collections, and look at the pile of beginProcess/endProcessing events wrapped around each application-level handler.

**Expected behavior**

Unless the user asks otherwise, all of those system-level wrapper handlers should be treated as overhead, or fully attributed to the innermost handler.

**Screenshots**

### PR DESCRIPTION
**Pull request by lifflander**
Fixes #631

### CODE REVIEW

File: src/vt/configs/arguments/args.cc [hunk 1]
```diff
@@ -78,6 +78,11 @@ namespace vt { namespace arguments {
 /*static*/ std::string ArgConfig::vt_trace_dir          = "";
 /*static*/ int32_t     ArgConfig::vt_trace_mod          = 0;
 /*static*/ int32_t     ArgConfig::vt_trace_flush_size   = 0;
+/*static*/ bool        ArgConfig::vt_trace_sys_all        = false;
```
Comment (pnstickne) [inline src/vt/configs/arguments/args.cc]: It feels like this is overall N-flags is a less-than-ideal approach to handle sets..

File: src/vt/configs/arguments/args.h [hunk 2]
```diff
@@ -158,6 +163,19 @@ inline bool user1() { return ArgConfig::vt_user_1; }
 inline bool user2() { return ArgConfig::vt_user_2; }
 inline bool user3() { return ArgConfig::vt_user_3; }
 
+inline bool traceTerm() {
```
Comment (pnstickne) [inline src/vt/configs/arguments/args.h]: Non-consistency here :|

It seems like the final 'state' if internal state variables should be handled separately from the source of the variable in a post-argument stage. There is a certain branch that I'd love to *continue* such work on.. 🔢

File: src/vt/messaging/active.impl.h [hunk 3]
```diff
@@ -62,6 +63,53 @@ void ActiveMessenger::setTermMessage(MsgPtrT const msg) {
...
+
+template <typename MsgPtrT>
+void ActiveMessenger::makeTraceCreationSend(
+  MsgPtrT msg, HandlerType const handler, auto_registry::RegistryTypeEnum type,
+  MsgSizeType msg_size, bool is_bcast
+) {
+  #if backend_check_enabled(trace_enabled)
+    auto cur_event = envelopeGetTraceEvent(msg->env);
+    if (cur_event == trace::no_trace_event) {
+      trace::TraceEntryIDType ep = auto_registry::handlerTraceID(handler, type);
```
Comment (pnstickne) [inline src/vt/messaging/active.impl.h]: These names.. always double-take on Entry vs Event :|

File: src/vt/runnable/collection.impl.h [hunk 4]
```diff
@@ -69,7 +69,12 @@ template <typename MsgT, typename ElementT>
     trace::TraceEntryIDType trace_id = auto_registry::handlerTraceID(
       handler, reg_enum
     );
-    trace::TraceEventIDType trace_event = theMsg()->getCurrentTraceEvent();
+    // Note: get the event from the envelope to get the semantic connection for
+    // collections---no the current thing running in the queue
```
Comment (pnstickne) [inline src/vt/runnable/collection.impl.h]: "not"

File: src/vt/runnable/general.impl.h [hunk 5]
```diff
@@ -121,7 +126,9 @@ template <typename MsgT>
   }
 
   #if backend_check_enabled(trace_enabled)
-    theTrace()->endProcessing(trace_id, msg_size, trace_event, from_node);
+    if (is_traced) {
+      theTrace()->endProcessing(trace_id, msg_size, trace_event, from_node);
```
Comment (pnstickne) [inline src/vt/runnable/general.impl.h]: Would be nice to `theTrace()->endProcessing(id_from_before)` :|

File: src/vt/utils/demangle/demangle.cc [hunk 6]
```diff
@@ -134,7 +134,10 @@ TemplateExtract::getBarename(std::string const& typestr) {
   size_t d = getNameDivide(typestr, s, s, 0);
 
   // skip "::" divider
-  d += 2;
+  if (typestr[d] == ':') {
```
Comment (pnstickne) [inline src/vt/utils/demangle/demangle.cc]: Other PR is over - just note for rebase.

File: src/vt/vrt/collection/manager.impl.h [hunk 7]
```diff
@@ -643,6 +643,7 @@ template <typename>
   );
   if (msg->isRoot()) {
     auto new_msg = makeMessage<CollectionConsMsg>(*msg);
+    theMsg()->setCollectionMessage(new_msg);
```
Comment (pnstickne) [inline src/vt/vrt/collection/manager.impl.h]: I really want to flip these .. part of SharedMsgPtr work.

File: src/vt/trace/trace.cc [hunk 8]
```diff
@@ -124,10 +124,21 @@ Trace::Trace() { }
...
+      theTrace()->endIdle();
+    }
+  #endif
+}
+
 void Trace::initialize() {
   theSched()->registerTrigger(
     sched::SchedulerEvent::BeginIdle, traceBeginIdleTrigger
   );
+  theSched()->registerTrigger(
```
Comment (pnstickne) [inline src/vt/trace/trace.cc]: There is other code in trace.cc which will 'end a trace event when another even is encountered'.

If the begin/end are accurate it might worthwhile to eliminate that logic. (Any overlaps would represent ACTUAL overlaps then.)

File: src/vt/messaging/active.impl.h [hunk 9]
```diff
@@ -62,6 +63,53 @@ void ActiveMessenger::setTermMessage(MsgPtrT const msg) {
...
+      if (not is_bcast) {
+        trace::TraceEventIDType event = theTrace()->messageCreation(ep, msg_size);
+        envelopeSetTraceEvent(msg->env, event);
+      } else {
+        trace::TraceEventIDType event = theTrace()->messageCreationBcast(
+          ep, msg_size
+        );
+        envelopeSetTraceEvent(msg->env, event);
```
Comment (pnstickne) [inline src/vt/messaging/active.impl.h]: Common to both branches.

Comment (pnstickne) [reply src/vt/messaging/active.impl.h]: trace::TraceEventIDType event;
      if (not is_bcast) {
        event = theTrace()->messageCreation(ep, msg_size);
      } else {
        event = theTrace()->messageCreationBcast(ep, msg_size);
      }
      envelopeSetTraceEvent(msg->env, event);

File: src/vt/messaging/active.impl.h [hunk 10]
```diff
@@ -62,6 +63,53 @@ void ActiveMessenger::setTermMessage(MsgPtrT const msg) {
...
   envelopeSetPriority(msg->env, sys_min_priority);
 #endif
+#if backend_check_enabled(trace_enabled)
+  //fmt::print("arguments::traceTerm()={}\n",arguments::traceTerm());
+  envelopeSetTraceThis(msg->env, arguments::traceTerm());
+#endif
+}
+
+template <typename MsgPtrT>
+void ActiveMessenger::setLocationMessage(MsgPtrT const msg) {
```
Comment (pnstickne) [inline src/vt/messaging/active.impl.h]: These names were/are confusing to me, as as reader. The information that it is trace-related is lost.

Compare:
      
      enableLocationTrace

Or

      enableTrace(msg, additive_flags)

Or, pretty much anything indicating it's a trace :|

File: src/vt/messaging/envelope/envelope_get.impl.h [hunk 11]
```diff
@@ -87,6 +87,11 @@ template <typename Env>
 inline trace::TraceEventIDType envelopeGetTraceEvent(Env& env) {
   return reinterpret_cast<Envelope*>(&env)->trace_event;
 }
+
+template <typename Env>
+inline bool envelopeGetTraceThis(Env& env) {
+  return reinterpret_cast<Envelope*>(&env)->trace_this;
```
Comment (pnstickne) [inline src/vt/messaging/envelope/envelope_get.impl.h]: Possibly `trace_enabled` instead, for parity and to break association with `this`.

File: src/vt/messaging/envelope/envelope_setup.impl.h [hunk 12]
```diff
@@ -70,6 +70,10 @@ inline void envelopeInit(Env& env) {
   envelopeSetPriority(env, min_priority);
   envelopeSetPriorityLevel(env, 0);
 # endif
+# if backend_check_enabled(trace_enabled)
+  envelopeSetTraceThis(env, true);
+  envelopeSetTraceEvent(env, trace::no_trace_event);
```
Comment (pnstickne) [inline src/vt/messaging/envelope/envelope_setup.impl.h]: From previous comment (which I now partially retract), it would then be something like:

     envelopeSetTraceEvent(env, trace::enable_trace_sentinel);

File: src/vt/trace/trace.cc (hunk 8 above)
Comment (pnstickne) [reply src/vt/trace/trace.cc]: Also, the event could be emitted *immediately* and thus avoid the internal trace idle flags.

File: src/vt/configs/arguments/args.cc (hunk 1 above)
Comment (pnstickne) [reply src/vt/configs/arguments/args.cc]: e.g, consider arg syntax:

     -vt_trace sys,user,..

**Comment by pnstickne** [comment]
Codacy wants to steal my information to login :|

**Comment by pnstickne** [comment]
I still believe the event output stream can be .. 'optimized' in terms of how writes occur.

That would likely require a new contract definition and client handling.

File: src/vt/messaging/active.impl.h (hunk 10 above)
Comment (pnstickne) [reply src/vt/messaging/active.impl.h]: Uhg.. now I see the naming :|

File: src/vt/trace/trace.cc (hunk 8 above)
Comment (lifflander) [reply src/vt/trace/trace.cc]: There is a reason this is required now. We are not emitting system events, so the trace should show overhead (black) instead of ideal. Thus we need to end the idle explicitly.

File: src/vt/configs/arguments/args.cc (hunk 1 above)
Comment (pnstickne) [reply src/vt/configs/arguments/args.cc]: Later time..

File: src/vt/runnable/general.impl.h (hunk 5 above)
Comment (pnstickne) [reply src/vt/runnable/general.impl.h]: Incoming 🍡

File: src/vt/trace/trace.cc (hunk 8 above)
Comment (pnstickne) [reply src/vt/trace/trace.cc]: @lifflander Alright, I can see for the second case: what about the first?

That is, if begin + end idle events mark the actual idle time, use them as points to emit events. A new event (even if it were somehow to be trigged 'when idle') would not implicit trigger and end idle event. Any overlaps would represent event emission errors (or even possibly valid overlaps).

Comment (pnstickne) [reply src/vt/trace/trace.cc]: Wrt above https://github.com/DARMA-tasking/vt/blob/b53076be583d79a989ccd108ad504119484e863a/src/vt/trace/trace.cc#L579

Current implicit-end (which works on state, vs immediate event emitting):

    // close any idle event as soon as we encounter any other type of event
    if (idle_begun_ and
        log->type != TraceConstantsType::BeginIdle and
        log->type != TraceConstantsType::EndIdle) {
      endIdle();
    }

Comment (pnstickne) [reply src/vt/trace/trace.cc]: Assuming that no other traces can be written WHILE in idle, between the idle-start and idle-end callbacks, the above code / state management is stale. (See new vs potentially different forms above.)

Comment (pnstickne) [reply src/vt/trace/trace.cc]: And with the state reduction:

```
/*static*/ void Trace::traceBeginIdleTrigger() {
  #if backend_check_enabled(trace_enabled)
    theTrace()->beginIdle();
  #endif
}

/*static*/ void Trace::traceEndIdleTrigger() {
  #if backend_check_enabled(trace_enabled)
    theTrace()->endIdle();
  #endif
}
```

File: src/vt/messaging/active.impl.h [hunk 13]
```diff
@@ -62,6 +63,51 @@ void ActiveMessenger::setTermMessage(MsgPtrT const msg) {
...
+#if backend_check_enabled(trace_enabled)
```
Comment (pnstickne) [inline src/vt/messaging/active.impl.h]: Okay, these names are still confusing - slept on it a day, although the previous `traceXYZ` was incomplete in scope.

A name similar to `markAsLocationMessage` would read easier for me overall, and fit in with `setTermMessage` which does more than tracing. Giving it a go:

- markAsTermMessage
- makeAsLocationMessage
- markAsSerialMsgMessage
- markAsCollectionMessage

Comment (lifflander) [reply src/vt/messaging/active.impl.h]: Ok, that's a good idea. Will update

**Comment by pnstickne** [comment]
Any reason not to move to develop? (minus checks)

File: src/vt/messaging/envelope/envelope_set.impl.h [hunk 14]
```diff
@@ -123,6 +123,11 @@ template <typename Env>
 inline void envelopeSetTraceEvent(Env& env, trace::TraceEventIDType const& evt) {
   reinterpret_cast<Envelope*>(&env)->trace_event = evt;
 }
+
+template <typename Env>
+inline void envelopeSetTraceThis(Env& env, bool in) {
+  reinterpret_cast<Envelope*>(&env)->trace_this = in;
```
Comment (PhilMiller) [inline src/vt/messaging/envelope/envelope_set.impl.h]: Should this be `static_cast` as seen in other recent issues?

**Comment by lifflander** [comment]
> Any reason not to move to develop? (minus checks)

I fix the small issues and get this on develop.

File: src/vt/messaging/envelope/envelope_get.impl.h (hunk 11 above)
Comment (PhilMiller) [inline src/vt/messaging/envelope/envelope_get.impl.h]: `static_cast` here - let's not make things worse. Or just add a commit correcting all of these

**Comment by pnstickne** [comment]
@lifflander Ready to move to PR-ready status?

**Comment by lifflander** [comment]
@PhilMiller @pnstickne I plan to address these and get this merged today.

File: src/vt/configs/arguments/args.h (hunk 2 above)
Comment (lifflander) [reply src/vt/configs/arguments/args.h]: I agree this needs to be addressed more broadly, tabling this for now so i can move forward on this PR.

File: src/vt/runnable/collection.impl.h (hunk 4 above)
Comment (lifflander) [reply src/vt/runnable/collection.impl.h]: Fixed.

File: src/vt/utils/demangle/demangle.cc (hunk 6 above)
Comment (lifflander) [reply src/vt/utils/demangle/demangle.cc]: Rebased out

File: src/vt/messaging/active.impl.h (hunk 9 above)
Comment (lifflander) [reply src/vt/messaging/active.impl.h]: Fixed.

File: src/vt/messaging/envelope/envelope_get.impl.h (hunk 11 above)
Comment (lifflander) [reply src/vt/messaging/envelope/envelope_get.impl.h]: Addressed this

File: src/vt/messaging/active.impl.h (hunk 10 above)
Comment (lifflander) [reply src/vt/messaging/active.impl.h]: Fixed

File: src/vt/messaging/envelope/envelope_set.impl.h (hunk 14 above)
Comment (lifflander) [reply src/vt/messaging/envelope/envelope_set.impl.h]: Yes, but I'm going to leave this for another PR to cleanup and test.

File: src/vt/messaging/envelope/envelope_get.impl.h (hunk 11 above)
Comment (lifflander) [reply src/vt/messaging/envelope/envelope_get.impl.h]: Again, I don't want to mess with now and make sure the compiler doesn't produce a bad offset in some way.

File: src/vt/trace/trace.cc (hunk 8 above)
Comment (lifflander) [reply src/vt/trace/trace.cc]: I agree, but want this done in a separate issue. Created one for this; https://github.com/DARMA-tasking/vt/issues/685

File: src/vt/messaging/envelope/envelope_get.impl.h (hunk 11 above)
Comment (lifflander) [reply src/vt/messaging/envelope/envelope_get.impl.h]: Created a separate issue for this: #684

File: src/vt/handler/handler.h [hunk 15]
```diff
@@ -68,10 +68,21 @@ static constexpr HandlerType const blank_handler = 0;
 static constexpr BitCountType const auto_num_bits = 1;
 static constexpr BitCountType const functor_num_bits = 1;
 static constexpr BitCountType const objgroup_num_bits = 1;
+
+#if backend_check_enabled(trace_enabled)
+static constexpr BitCountType const trace_num_bits = 1;
```
Comment (pnstickne) [inline src/vt/handler/handler.h]: Might be reasonable to leave in all builds.

File: src/vt/messaging/envelope/envelope_set.h [hunk 16]
```diff
@@ -186,6 +186,15 @@ inline void envelopeSetPriorityLevel(Env& env, PriorityLevelType priority_level)
...
 inline void envelopeSetTraceEvent(Env& env, trace::TraceEventIDType const& evt);
+
+/**
+ * \brief Set whether this envelope is traced at runtime
+ *
+ * \param[in,out] env the envelope
+ * \param[in] in whether it should be traced
+ */
+template <typename Env>
+inline void envelopeSetTraceRuntimeEnabled(Env& env, bool in);
```
Comment (pnstickne) [inline src/vt/messaging/envelope/envelope_set.h]: `in` could be a wee bit more descriptive.

File: src/vt/runnable/collection.h [hunk 17]
```diff
@@ -54,7 +54,8 @@ struct RunnableCollection {
   static void run(
```
Comment (pnstickne) [inline src/vt/runnable/collection.h]: Might be worth considering overloads so the basic forms (no/reduced optionals) don't deal with extra information.

File: src/vt/runnable/general.impl.h [hunk 18]
```diff
@@ -76,16 +76,17 @@ template <typename MsgT>
...
 #if backend_check_enabled(trace_enabled)
   trace::TraceProcessingTag processing_tag;
-  {
+  bool is_traced = HandlerManagerType::isHandlerTrace(handler);
+  if (is_traced) {
     trace::TraceEntryIDType trace_id = auto_registry::handlerTraceID(
       handler, auto_registry::RegistryTypeEnum::RegGeneral
     );
-    trace::TraceEventIDType trace_event = trace::no_trace_event;
+    trace::TraceEventIDType  trace_event = trace::no_trace_event;
```
Comment (pnstickne) [inline src/vt/runnable/general.impl.h]: Extra space.

File: src/vt/runnable/general.impl.h [hunk 19]
```diff
@@ -123,7 +124,9 @@ template <typename MsgT>
   }
 
 #if backend_check_enabled(trace_enabled)
-  theTrace()->endProcessing(processing_tag);
+  if (is_traced) {
+    theTrace()->endProcessing(processing_tag);
```
Comment (pnstickne) [inline src/vt/runnable/general.impl.h]: If the processing_tag is the default value then it will suppress inside the `endProcessing` function, so the condition here can be removed.

File: src/vt/runnable/general.impl.h (hunk 18 above)
Comment (lifflander) [inline src/vt/runnable/general.impl.h]: Oops, whitespace here is off

File: src/vt/runtime/runtime.cc [hunk 20]
```diff
@@ -573,6 +573,32 @@ void Runtime::printStartupBanner() {
       auto f12 = opt_inverse("--vt_trace_flush_size", f11);
       fmt::print("{}\t{}{}", vt_pre, f12, reset);
     }
+    if (not ArgType::vt_trace_sys_all) {
```
Comment (pnstickne) [inline src/vt/runtime/runtime.cc]: Could simplify lots of this logic if just specify state (no on/off etc.).

File: src/vt/serialization/messaging/serialized_messenger.impl.h [hunk 21]
```diff
@@ -309,8 +309,10 @@ template <typename MsgT, typename BaseT>
   auto const& total_size = ptr_size + msg_size + han_size + size_size;
   auto const& tag = no_tag;
   if (is_bcast) {
+    theMsg()->markAsSerialMsgMessage(msg);
```
Comment (pnstickne) [inline src/vt/serialization/messaging/serialized_messenger.impl.h]: Could be moved outside of condition.

File: src/vt/serialization/messaging/serialized_messenger.impl.h [hunk 22]
```diff
@@ -415,13 +418,24 @@ template <typename MsgT, typename BaseT>
...
     return theMsg()->broadcastMsg<PayloadMsg,payloadMsgHandler>(
       payload_msg.get()
     );
   } else {
     auto const& total_size = ptr_size + sys_size;
 
-    sys_msg->handler = han;
+    auto han_modified = han;
+
+#   if backend_check_enabled(trace_enabled)
```
Comment (pnstickne) [inline src/vt/serialization/messaging/serialized_messenger.impl.h]: Several different layout variations of `#` used.

File: src/vt/serialization/messaging/serialized_messenger.impl.h [hunk 23]
```diff
@@ -415,13 +418,24 @@ template <typename MsgT, typename BaseT>
...
 
+    theMsg()->markAsSerialMsgMessage(payload_msg);
     return theMsg()->broadcastMsg<PayloadMsg,payloadMsgHandler>(
       payload_msg.get()
     );
   } else {
     auto const& total_size = ptr_size + sys_size;
 
-    sys_msg->handler = han;
+    auto han_modified = han;
```
Comment (pnstickne) [inline src/vt/serialization/messaging/serialized_messenger.impl.h]: Maybe `traceable_han` or some such. Definitely good to have a different variable in either case.

File: src/vt/runtime/runtime.cc (hunk 20 above)
Comment (lifflander) [reply src/vt/runtime/runtime.cc]: I like the symmetry here. Breaking out earlier is easier to read

File: src/vt/runnable/general.impl.h (hunk 19 above)
Comment (lifflander) [reply src/vt/runnable/general.impl.h]: I like the symmetry here. Breaking out earlier is easier to read I think

File: src/vt/topos/location/location.impl.h [hunk 24]
```diff
@@ -406,6 +408,7 @@ void EntityLocationCoord<EntityID>::routeMsgNode(
     envelopeGetRef(msg->env), msg->getLocFromNode(), print_ptr(msg.get()),
     epoch
   );
+  theMsg()->markAsLocationMessage(msg);
```
Comment (pnstickne) [inline src/vt/topos/location/location.impl.h]: Seems odd snuggled to the debug (instead of the following if).

File: src/vt/topos/location/location.impl.h [hunk 25]
```diff
@@ -716,6 +737,7 @@ template <typename EntityID>
           inst, entity, event_id, ask_node, home_node
         );
         msg2->setResolvedNode(node);
+        theMsg()->markAsLocationMessage(msg2);
```
Comment (pnstickne) [inline src/vt/topos/location/location.impl.h]: Going all the way back, these to be exposed as `theMsg()` for consumers? If not, having a clear `\internal` mark on the Doxygen would be helpful encouragement to not use.

File: src/vt/topos/location/location.impl.h (hunk 24 above)
Comment (lifflander) [reply src/vt/topos/location/location.impl.h]: Fixed

File: src/vt/serialization/messaging/serialized_messenger.impl.h (hunk 23 above)
Comment (lifflander) [reply src/vt/serialization/messaging/serialized_messenger.impl.h]: Fixed

File: src/vt/serialization/messaging/serialized_messenger.impl.h (hunk 22 above)
Comment (lifflander) [reply src/vt/serialization/messaging/serialized_messenger.impl.h]: I recently started switching to starting with `#` and then indenting because I think techically that's the correct way according to the standard. I haven't gone through and updated all the code. I will create an issue to unify the style across the codebase.

https://github.com/DARMA-tasking/vt/issues/686

File: src/vt/serialization/messaging/serialized_messenger.impl.h (hunk 21 above)
Comment (lifflander) [reply src/vt/serialization/messaging/serialized_messenger.impl.h]: Done

File: src/vt/runnable/general.impl.h (hunk 18 above)
Comment (lifflander) [reply src/vt/runnable/general.impl.h]: Fixed

Comment (lifflander) [reply src/vt/runnable/general.impl.h]: Fixed

File: src/vt/runnable/collection.h (hunk 17 above)
Comment (lifflander) [reply src/vt/runnable/collection.h]: Agreed, good task for the future

File: src/vt/messaging/envelope/envelope_set.h (hunk 16 above)
Comment (lifflander) [reply src/vt/messaging/envelope/envelope_set.h]: Done

File: src/vt/runtime/runtime.cc (hunk 20 above)
Comment (lifflander) [reply src/vt/runtime/runtime.cc]: Agreed, let's do this in a separate issue

File: src/vt/handler/handler.h (hunk 15 above)
Comment (lifflander) [reply src/vt/handler/handler.h]: Done

File: src/vt/topos/location/location.impl.h (hunk 25 above)
Comment (lifflander) [reply src/vt/topos/location/location.impl.h]: I think this will require a larger refactor into a new category (internal to VT access to `ActiveMessenger`). I agree this needs to be done. For now, I am tabling this.

Comment (lifflander) [reply src/vt/topos/location/location.impl.h]: https://github.com/DARMA-tasking/vt/issues/687

**Comment by pnstickne** [comment]
Phone (mobile hotspot) ran out of power earlier D:

File: src/vt/messaging/active.cc [hunk 26]
```diff
@@ -262,21 +262,31 @@ EventType ActiveMessenger::sendMsgSized(
...
+    HandlerManagerType::setHandlerTrace(
+      handler, envelopeGetTraceRuntimeEnabled(msg->env)
+    );
+
+    // Update the handler with trace bits now set appropriately
+    envelopeSetHandler(msg->env, handler);
+
+    if (not is_bcast or (is_bcast and dest == this_node_)) {
+      // auto cur_event = envelopeGetTraceEvent(msg->env);
+      // if (cur_event == trace::no_trace_event) {
```
Comment (PhilMiller) [inline src/vt/messaging/active.cc]: What's with the commented out code left here?

File: src/vt/vrt/collection/manager.impl.h [hunk 27]
```diff
@@ -1002,6 +1014,19 @@ messaging::PendingSend CollectionManager::broadcastMsgUntypedHandler(
 
   auto msg = promoteMsg(raw_msg);
 
+  #if backend_check_enabled(trace_enabled)
+    // Create the trace creation event for the broadcast here to connect it a
```
Comment (PhilMiller) [inline src/vt/vrt/collection/manager.impl.h]: Missing a word "connect it **to** a higher semantic level"

File: src/vt/vrt/collection/manager.impl.h [hunk 28]
```diff
@@ -1424,6 +1449,21 @@ messaging::PendingSend CollectionManager::sendMsgUntypedHandler(
       }
     #endif
 
+    #if backend_check_enabled(trace_enabled)
+      // Create the trace creation event here to connect it a higher semantic
```
Comment (PhilMiller) [inline src/vt/vrt/collection/manager.impl.h]: Again, missing 'to'

**Comment by PhilMiller** [comment]
Would it be worth considering this for beta.5 as well? Besides improving the quality of the traces, it would also sharply reduce their size when not tracing system-level events separately.
