### PR TITLE
1704 Fix envelope locking error in envelope and add test

### LINKED ISSUE #1704: Reduction to callback fails when root rank has zero contributions
**Describe the bug**
Here is the minimal reproducer. Fails when run like this:

`mpirun -n 2 ./reproducer`

```C++
using ReduceMsg = vt::collective::ReduceTMsg<int>;

struct MyObjGroup {
  void handler(ReduceMsg* msg) {
    fmt::print("Reduce complete at {} value {}\n", vt::theContext()->getNode(), msg->getVal());
  }
};

vt::objgroup::proxy::Proxy<MyObjGroup> objgroup_proxy;

struct Hello : vt::Collection<Hello, vt::Index1D> {

  using TestMsg = vt::CollectionMessage<Hello>;

  void doWork(TestMsg* msg) {
    fmt::print("{}: Hello from {}\n", vt::theContext()->getNode(), this->getIndex());

    // Get the proxy for the collection
    auto proxy = this->getCollectionProxy();

    // Create a callback for when the reduction finishes
    auto cb = vt::theCB()->makeBcast<MyObjGroup,ReduceMsg,&MyObjGroup::handler>(objgroup_proxy);

    // Create and send the reduction message holding an int
    auto red_msg = vt::makeMessage<ReduceMsg>(this->getIndex().x());
    proxy.reduce<vt::collective::PlusOp<int>>(red_msg.get(),cb);
  }
};

vt::NodeType map(vt::Index1D* idx, vt::Index1D* max_idx, vt::NodeType num_nodes) {
  //return idx->x() == 0 ? 0 : (idx->x() % (num_nodes-1))+1;
  return (idx->x() % (num_nodes-1))+1;
}

int main(int argc, char** argv) {
  vt::initialize(argc, argv);

  vt::NodeType this_node = vt::theContext()->getNode();

  int32_t num_elms = 2;

  objgroup_proxy = vt::theObjGroup()->makeCollective<MyObjGroup>();

  auto range = vt::Index1D(num_elms);
  auto proxy = vt::makeCollection<Hello>()
    .bounds(range)
    .mapperFunc<map>()
    .bulkInsert()
    .wait();

  if (this_node == 0) {
    proxy.broadcast<Hello::TestMsg,&Hello::doWork>();
  }

  vt::finalize();

  return 0;
}
```

### PR DESCRIPTION
**Pull request by lifflander**
Fixes #1704

### CODE REVIEW

**Review by cz4rs — APPROVED** [review]
Looks good to me!

File: tests/unit/collectives/test_collectives_reduce.cc [hunk 1]
```diff
@@ -47,7 +47,7 @@
 #include "data_message.h"
 #include "test_collectives_reduce.h"
```
Comment (cz4rs) [inline tests/unit/collectives/test_collectives_reduce.cc:49]:
```suggestion
#include "test_helpers.h"

```

**Review by JacobDomagala — APPROVED** [review]

**Review by nlslatt — APPROVED** [review]
Solves my crash.
