### PR TITLE
#591 Fix bad captured stack pointer

### LINKED ISSUE #591: Bug in group (tutorial 32 ranks crash)
**Describe the bug**

**To Reproduce**
1. Example/test/snippet of code that fails
2. Compiler, platform, libraries
3. Run command: number of processors, threading options, etc.

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - Supercomputer or desktop [e.g., Trinity, Sierra)
 - Compiler environment [e.g., clang-3.9, gcc8]
 - Libraries [e.g., mpich-2, openmpi)
 - Commit ID or release of VT [e.g., vt-1.0.0]

**Additional context**

### PR DESCRIPTION
**Pull request by lifflander**
Fixes #591

### CODE REVIEW

File: src/vt/group/group_manager.cc [hunk 1]
```diff
@@ -375,9 +375,13 @@ EventType GroupManager::sendGroupCollective(
       return no_event;
     }
   } else if (in_group && !group_ready) {
-    local_collective_group_info_.find(group)->second->readyAction([=]{
-      theGroup()->sendGroupCollective(base,from,size,is_root,deliver);
-    });
+    local_collective_group_info_.find(group)->second->readyAction(
```
Comment (pnstickne) [inline src/vt/group/group_manager.cc]: Did I call it or what? :D

Comment (pnstickne) [reply src/vt/group/group_manager.cc]: (Well, tangentially anyway..)

File: src/vt/group/group_manager.cc [hunk 2]
```diff
@@ -375,9 +375,13 @@ EventType GroupManager::sendGroupCollective(
...
+      [base,from,size,is_root]{
+        // Do not capture deliver, it's a pointer to stack memory
+        bool dummy;
```
Comment (pnstickne) [inline src/vt/group/group_manager.cc]: Can be any value in? Although with [=] it could still have done a *copy* capture, no?

Comment (PhilMiller) [reply src/vt/group/group_manager.cc]: I'd stick with strictly referring to that as capture *by value* - in this case, the value of the pointer, which contained the address of a local stack variable. Subsequent dereferencing of such a pointer is, of course, an error, since it occurs after the end of the lifetime of the object referenced.

I don't think a C++ compiler could reliably warn about this, since it can't tell when the lambda will be called. The Rust compiler probably could, since it would require that the lifetime of the lamdba not exceed the lifetime of any object on which it holds a borrowed reference. The C++ Core Guidelines effort may facilitate doing more Rust-like analysis in C++, but that's not here yet.

File: src/vt/group/group_manager.cc (hunk 1 above)
Comment (lifflander) [reply src/vt/group/group_manager.cc]: Yes, you did
