### PR TITLE
769 gossip bugs

### LINKED ISSUE #769: Fix bugs in GossipLB---partition getting worse
**Describe the bug**
Observing on Mutrino that it gets worse sometimes.

### PR DESCRIPTION
**Pull request by lifflander**
Fixes #769 

- Fix broken CMF adding overloaded nodes
- Fix missing sync at iteration start causing load 0.0 to propagate

### CODE REVIEW

File: src/vt/vrt/collection/balance/gossiplb/gossiplb.cc [hunk 1]
```diff
@@ -177,10 +179,20 @@ void GossipLB::inform() {
...
+    k_max_, k_cur_, is_underloaded_, is_overloaded_, this_new_load_
   );
 
+  setup_done_ = false;
+
+  auto cb = theCB()->makeBcast<GossipLB, ReduceMsgType, &GossipLB::setupDone>(proxy_);
+  auto msg = makeMessage<ReduceMsgType>();
+  proxy_.reduce(msg.get(), cb);
+
+  while (not setup_done_) {
```
Comment (pnstickne) [inline src/vt/vrt/collection/balance/gossiplb/gossiplb.cc:192]: There is a cute little construct for this in some branch :'(
