### PR TITLE
1122 elementstats is leaking

### LINKED ISSUE #1122: ElementStats is leaking memory from previous phases
**Describe the bug**
`ElementStats` inside collection elements is leaking memory.

### PR DESCRIPTION
**Pull request by nlslatt**
The vectors holding stats in ElementStats grow without bound.  This PR erases stats data for phases older than the lookback.

Fixes #1122

### CODE REVIEW

File: src/vt/vrt/collection/balance/elm_stats.h [hunk 1]
```diff
@@ -93,6 +92,17 @@ struct ElementStats {
   void setSubPhase(SubphaseType subphase);
   SubphaseType getSubPhase() const;
 
+  /**
+   * \internal \brief Cleanup after LB runs
+   */
+  void startIterCleanup(PhaseType phase, unsigned int look_back);
```
Comment (jstrzebonski) [inline src/vt/vrt/collection/balance/elm_stats.h:98]: I kind of don't like the name. Does it 'start' the cleaning up (so it gets started and continues), or just cleans up and move on?

Maybe simple `void cleanUp(...)` would be sufficient?

File: src/vt/vrt/collection/balance/elm_stats.h [hunk 2]
```diff
@@ -93,6 +92,17 @@ struct ElementStats {
...
+
+  // these are just for unit testing
+  std::size_t getLoadPhaseCount() const;
+  std::size_t getCommPhaseCount() const;
+  std::size_t getSubphaseLoadPhaseCount() const;
+  std::size_t getSubphaseCommPhaseCount() const;
```
Comment (jstrzebonski) [inline src/vt/vrt/collection/balance/elm_stats.h:104]: IMHO that's smelly code. We're adding some functions only to do unit tests. I would say that it might be better to make it possible to somehow inject ElementStats-ish class into `Migratable`. That way we could write a struct deriving from ElementStats with added test functionalities such as those, and have it explicitly for unit testing.

Such refactoring might get big, so maybe a separate issue for doing this would be a good idea.

File: src/vt/vrt/collection/balance/elm_stats.h [hunk 3]
```diff
@@ -110,12 +120,12 @@ struct ElementStats {
   bool cur_time_started_ = false;
   TimeType cur_time_ = 0.0;
   PhaseType cur_phase_ = fst_lb_phase;
-  std::vector<TimeType> phase_timings_ = {};
-  std::vector<CommMapType> comm_ = {};
+  std::unordered_map<PhaseType, TimeType> phase_timings_ = {};
+  std::unordered_map<PhaseType, CommMapType> comm_ = {};
```
Comment (jstrzebonski) [inline src/vt/vrt/collection/balance/elm_stats.h:124]: We have `phase_timings`, `subphase_timings_` and `subphase_comm_`. Could we rename this (for consistency) to `phase_comm_`?

File: src/vt/vrt/collection/balance/elm_stats.h [hunk 4]
```diff
@@ -110,12 +120,12 @@ struct ElementStats {
...
 
   SubphaseType cur_subphase_ = 0;
-  std::vector<std::vector<TimeType>> subphase_timings_ = {};
-  std::vector<std::vector<CommMapType>> subphase_comm_ = {};
+  std::unordered_map<PhaseType, std::vector<TimeType>> subphase_timings_ = {};
+  std::unordered_map<PhaseType, std::vector<CommMapType>> subphase_comm_ = {};
```
Comment (jstrzebonski) [inline src/vt/vrt/collection/balance/elm_stats.h:128]: This might not make much sense (performance/memory overhead?), but if we change this to `unordered_map<PhaseType, unordered_map<SubphaseType, ...>>` we might simplify code by getting rid of all `resize()`s and `at()`s.

File: src/vt/vrt/collection/balance/elm_stats.h (hunk 1 above)
Comment (nlslatt) [reply src/vt/vrt/collection/balance/elm_stats.h:98]: The name was set to match what's being used in `NodeStats`, but you're right that it needs a better name.  I'm calling it `releaseStatsFromUnneededPhases` now.

File: src/vt/vrt/collection/balance/elm_stats.h (hunk 3 above)
Comment (nlslatt) [reply src/vt/vrt/collection/balance/elm_stats.h:124]: Agreed.  Making the change.

File: src/vt/vrt/collection/balance/elm_stats.h (hunk 2 above)
Comment (nlslatt) [reply src/vt/vrt/collection/balance/elm_stats.h:99]: I understand your complaint, but I don't fully understand your suggested solution.  Can you please elaborate?

File: tests/unit/collection/test_lbstats_retention.cc [hunk 5]
```diff
@@ -0,0 +1,226 @@
...
+
+    #if vt_check_enabled(lblite)
+      if (phase > phases_needed) {
+        // syncNextPhase will have caused timings to be added for the
+        // next phase already
+        EXPECT_EQ(load_phase_count, phases_needed + 1);
+        EXPECT_EQ(sp_load_phase_count, phases_needed + 1);
+
+        EXPECT_EQ(comm_phase_count, phases_needed);
+        EXPECT_EQ(sp_comm_phase_count, phases_needed);
```
Comment (PhilMiller) [inline tests/unit/collection/test_lbstats_retention.cc:85]: The offset between the timing and communication structures after phase 0 is a bit bothersome. Is there a reasonable adjustment in the way these are kept that could equalize them?

**Review by PhilMiller — APPROVED** [review]
This all looks good to me. Your choice whether to address the mismatch I noted.

File: tests/unit/collection/test_lbstats_retention.cc (hunk 5 above)
Comment (nlslatt) [reply tests/unit/collection/test_lbstats_retention.cc:85]: The current phase as tracked by `ElementStats` is incremented by a call to `updatePhase` made from `syncNextPhase`.  That causes the timings for the calls to `syncNextPhase` to be added to the loads for the next phase, which is appropriate because `syncNextPhase` already consumed the loads for the current phase.  I haven't thought of any way to equalize them without breaking the correctness.

File: src/vt/vrt/collection/balance/elm_stats.h (hunk 2 above)
Comment (jstrzebonski) [reply src/vt/vrt/collection/balance/elm_stats.h:99]: That's far from the solution, just a suggestion to consider (probably) for the future.

Generally, I was thinking if some sort of dependency injection might be possible (and might make sense) in this case, so that all those functions could be moved to another class, let's say, `TestElementStats : public ElementStats {...};`, and that class could be then used for unit testing.

But again - I don't think that's an easy change, but rather sizeable refactoring. So if that sounds reasonable it might be worth to write an issue for it. And if not, that's OK with me.

**Comment by PhilMiller** [comment]
The failure of `141 - vt:*/TestNodeStatsDumper.test_node_stats_dumping_with_interval/*_proc_4` on clang-8/macosx/mpich looks like it could be real?

File: src/vt/vrt/collection/balance/elm_stats.cc [hunk 6]
```diff
@@ -147,17 +132,13 @@ void ElementStats::updatePhase(PhaseType const& inc) {
   );
 
   cur_phase_ += inc;
```
Comment (PhilMiller) [inline src/vt/vrt/collection/balance/elm_stats.cc:134]: Would ensuring equality of all of the structure sizes be as simple as accessing each of them here:

```c++
// Access all table entries for current phase, to ensure presence even if they're left empty
phase_timings_[cur_phase_];
subphase_timings_[cur_phase_];
phase_comm_[cur_phase_];
subphase_comm_[cur_phase_];
```

Comment (nlslatt) [reply src/vt/vrt/collection/balance/elm_stats.cc:134]: Oh, I think I misunderstood one of your previous comments.  Is your goal to eliminate the difference in sizes between the comm-based stats data and non-comm-based?  I interpreted what you said before as being concerned about the sizes of the non-comm-based ones jumping by 2 only at the end of the first phase.  I can make your suggested change.

**Comment by jstrzebonski** [comment]
> 
> 
> The failure of `141 - vt:*/TestNodeStatsDumper.test_node_stats_dumping_with_interval/*_proc_4` on clang-8/macosx/mpich looks like it could be real?

Don't want to say yes or now, but given that it failed only on one build it might be just flaky :'- (
https://github.com/DARMA-tasking/vt/issues/1110

File: src/vt/vrt/collection/balance/elm_stats.cc (hunk 6 above)
Comment (PhilMiller) [reply src/vt/vrt/collection/balance/elm_stats.cc:134]: Yeah, I was bothered by seeing the tests check for `phases_needed + 1` on some structures, and `phases_needed` on others.

Comment (nlslatt) [reply src/vt/vrt/collection/balance/elm_stats.cc:134]: Fixed.

File: tests/unit/collection/test_lbstats_retention.cc (hunk 5 above)
Comment (nlslatt) [reply tests/unit/collection/test_lbstats_retention.cc]: Fixed, now that I understand what you meant.

**Comment by nlslatt** [comment]
> > The failure of `141 - vt:*/TestNodeStatsDumper.test_node_stats_dumping_with_interval/*_proc_4` on clang-8/macosx/mpich looks like it could be real?
> 
> Don't want to say yes or now, but given that it failed only on one build it might be just flaky :'- (
> There's an issue for this test -> #1110

It definitely looks like a legitimate failure, but I'm not sure yet if it's related to my changes.

**Review by PhilMiller — APPROVED** [review]

File: src/vt/vrt/collection/balance/elm_stats.h (hunk 2 above)
Comment (nlslatt) [reply src/vt/vrt/collection/balance/elm_stats.h:99]: I'll leave it to @lifflander to make this call.

Comment (lifflander) [reply src/vt/vrt/collection/balance/elm_stats.h:99]: I think in this case, it's not worth doing any heavy refactor. These are const methods and shouldn't hurt anything. In general, we have this issue elsewhere so we could discuss a broader solution in separate work.

**Review by lifflander — APPROVED** [review]
Looks good to me
