### PR TITLE
#621 Termination clear out state after term detected

### LINKED ISSUE #621: Epochs not being cleared for state in TD
**Describe the bug**

**To Reproduce**
1. Example/test/snippet of code that fails
2. Compiler, platform, libraries
3. Run command: number of processors, threading options, etc.

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - Supercomputer or desktop [e.g., Trinity, Sierra)
 - Compiler environment [e.g., clang-3.9, gcc8]
 - Libraries [e.g., mpich-2, openmpi)
 - Commit ID or release of VT [e.g., vt-1.0.0]

**Additional context**

### PR DESCRIPTION
**Pull request by lifflander**
Fixes #621

### CODE REVIEW

File: src/vt/termination/dijkstra-scholten/comm.cc [hunk 1]
```diff
@@ -89,7 +89,27 @@ namespace vt { namespace term { namespace ds {
...
+}
+
+/*static*/ void StateDS::disengage(EpochType epoch) {
+  debug_print(
+    termds, node,
+    "StateDS::disengage: epoch={:x}\n", epoch
+  );
+
+  // We are likely inside code that references the map structure that holds DS
+  // terminators. We can remove it safely. So we will enqueue an action to do
```
Comment (PhilMiller) [inline src/vt/termination/dijkstra-scholten/comm.cc]: Is "can" a typo for "can't"?

File: src/vt/termination/dijkstra-scholten/comm.cc [hunk 2]
```diff
@@ -89,7 +89,27 @@ namespace vt { namespace term { namespace ds {
...
+  // the cleanup. This action must see if the DS term is still disengaged (it
+  // can easily be re-engaged after it disengages)
```
Comment (PhilMiller) [inline src/vt/termination/dijkstra-scholten/comm.cc]: This comment on outstanding references doesn't give me a whole lot of confidence that we won't have dangling reference bugs anyway. 

If we want to be safe against that, we can work with objects whose lifetimes actually track such references to specific epochs, rather than the raw epoch numbers.

Alternately, the interface presented by StateDS can be better encapsulated so that references don't leak out, and it handles operations on epochs by number regardless of what state they've ended up in.

File: src/vt/termination/term_window.h [hunk 3]
```diff
@@ -105,6 +105,11 @@ struct EpochWindow {
    */
   void closeEpoch(EpochType const& epoch);
 
+  /*
+   * Terminated an active epoch by adding it to the sett
```
Comment (PhilMiller) [inline src/vt/termination/term_window.h]: Typo here: 'sett'

File: src/vt/termination/termination.h [hunk 4]
```diff
@@ -157,7 +157,7 @@ struct TerminationDetector :
 
 private:
   TermStateType& findOrCreateState(EpochType const& epoch, bool is_ready);
-  void cleanupEpoch(EpochType const& epoch);
+  void cleanupEpoch(EpochType const& epoch, bool isRoot);
```
Comment (PhilMiller) [inline src/vt/termination/termination.h]: I'd be much happier if this were an `enum {ROOT, NON_ROOT}`

**Comment by PhilMiller** [comment]
I think your fixes are OK, but I'll have to spend a bunch more time with the surrounding code to be more confident.

File: src/vt/termination/dijkstra-scholten/comm.cc (hunk 1 above)
Comment (lifflander) [reply src/vt/termination/dijkstra-scholten/comm.cc]: Yes, should be can't

File: src/vt/termination/term_window.h (hunk 3 above)
Comment (lifflander) [reply src/vt/termination/term_window.h]: Fixed, this was a copy-paste error also

File: src/vt/termination/termination.h (hunk 4 above)
Comment (lifflander) [reply src/vt/termination/termination.h]: Switched to enum

File: src/vt/termination/dijkstra-scholten/comm.cc (hunk 2 above)
Comment (lifflander) [reply src/vt/termination/dijkstra-scholten/comm.cc]: I've improved the comment in the code. I agree with you about lifetimes, but that would be a major refactor. Are you comfortable with the code as is?

Comment (PhilMiller) [reply src/vt/termination/dijkstra-scholten/comm.cc]: If it holds up in practice for now, yeah, I'm fine going ahead with this.
