### PR TITLE
1111 Fix for large message sends

### LINKED ISSUE #1111: Active messenger fails when sending over 2 GiB of data due to MPI limitations
**Describe the bug**
Due to limitations in MPI, the code fails when sending a single payload over 2 GiB due to overflow.

### PR DESCRIPTION
**Pull request by lifflander**
Fixes #1111 

- Start with tests that fail for serialized/non-serialized messages

- ~Make a **major** improvement to how tests are being dispatched. Currently, tests are being ignored due to deficiencies in the gtest cmake. Pull in the latest gtest cmake and fix the bugs in that version of the cmake. **This is causing "new" tests to fail on this PR that weren't running before which I am systematically trying to fix**~
  - Addressed & merged in separate PR

- Implement "multi-sends" for serialized and non-serialized messages (now passing!)

- Add a new runtime argument `--vt_max_mpi_send_size=X` that defaults to `1ull << 30`.

- Use the new argument injector to set the size for testing to `16384` bytes

### CODE REVIEW

File: src/vt/messaging/active.cc [hunk 1]
```diff
@@ -248,6 +249,166 @@ EventType ActiveMessenger::sendMsgBytesWithPut(
...
 }
 
+struct MultiMsg : vt::Message {
+  using MessageParentType = vt::Message;
+  using TagsType = std::vector<MPI_TagType>;
+
+  vt_msg_serialize_required();
+
+  MultiMsg() = default;
+  MultiMsg(TagsType in_tags, NodeType in_from, MsgSizeType in_size)
```
Comment (lifflander) [inline src/vt/messaging/active.cc:259]: Codacy found an issue: [Function parameter 'in_tags' should be passed by const reference.](https://app.codacy.com/manual/lifflander/vt/pullRequest?prid=6334599)

**Comment by lifflander** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Clones removed
==============
+ src/vt/messaging/active.cc  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/lifflander/vt/pullRequest?prid=6334599&bid=20579140)

**Comment by lifflander** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones removed
==============
+ src/vt/messaging/active.cc  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/lifflander/vt/pullRequest?prid=6334599&bid=20579140)

**Comment by lifflander** [comment]
Currently failing unrelated tests:
```
The following tests FAILED:
        248 - vt:TestDiagnosticValue.test_diagnostic_value_2_proc_8 (Failed)
        255 - vt:TestGroup.test_group_range_construct_1_proc_2 (Failed)
        258 - vt:TestGroup.test_group_range_construct_1_proc_4 (Failed)
        282 - vt:*TestLocationRoute/*test_entity_cache_hits_proc_2 (Failed)
        291 - vt:*TestLocationRoute/*test_entity_cache_hits_proc_4 (Failed)
        292 - vt:*TestLocationRoute/*test_entity_cache_migrated_entity_proc_4 (Failed)
        300 - vt:*TestLocationRoute/*test_entity_cache_hits_proc_8 (Failed)
        301 - vt:*TestLocationRoute/*test_entity_cache_migrated_entity_proc_8 (Failed)
        434 - vt:*TestRDMAHandleCollection/*test_rdma_handle_collection_1_proc_2 (Failed)
        440 - vt:*TestRDMAHandleCollection/*test_rdma_handle_collection_1_proc_4 (Failed)
        446 - vt:*TestRDMAHandleCollection/*test_rdma_handle_collection_1_proc_8 (Failed)
```

**Comment by lifflander** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones removed
==============
+ src/vt/messaging/active.cc  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/lifflander/vt/pullRequest?prid=6334599&bid=20579140)

**Comment by lifflander** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones removed
==============
+ src/vt/messaging/active.cc  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/lifflander/vt/pullRequest?prid=6334599&bid=20579140)

**Comment by lifflander** [comment]
All the test failures should be fixed now.

**Comment by lifflander** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones removed
==============
+ src/vt/messaging/active.cc  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/lifflander/vt/pullRequest?prid=6334599&bid=20579140)

**Comment by lifflander** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones removed
==============
+ src/vt/messaging/active.cc  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/lifflander/vt/pullRequest?prid=6334599&bid=20579140)

File: src/vt/messaging/active.h [hunk 2]
```diff
@@ -97,65 +98,117 @@ static constexpr MsgSizeType const max_pack_direct_size = 512;
...
+    MPI_Status stat;
+    for (std::size_t i = 0; i < reqs.size();) {
+      VT_ALLOW_MPI_CALLS; // MPI_Test
+
+      MPI_Test(&reqs[i], &flag, &stat);
+      num_mpi_tests++;
+
+      if (flag == 0) {
+        ++i;
+        continue;
```
[the remark this answers is not in the document]
Comment (lifflander) [reply src/vt/messaging/active.h:192]: Fixed

File: src/vt/messaging/active.h [hunk 3]
```diff
@@ -1080,14 +1152,16 @@ struct ActiveMessenger : runtime::component::PollableComponent<ActiveMessenger>
    * \return whether it was successful or pending
    */
   bool recvDataMsg(
-    PriorityType priority, TagType const& tag, NodeType const& recv_node,
-    bool const& enqueue, RDMA_ContinuationDeleteType next = nullptr
+    int nchunks, PriorityType priority, TagType const& tag,
+    NodeType const& recv_node, bool const& enqueue,
```
[the remark this answers is not in the document]
Comment (lifflander) [reply src/vt/messaging/active.h:1156]: Changed `recv_node` to `sender`. There are a ton of reference arguments in the AM, so I'm going to leave that for another PR to make those extensive changes.

File: src/vt/pmpi/generate_mpi_wrappers.pl [hunk 4]
```diff
@@ -127,6 +127,7 @@ sub extract_defs {
     MPI_Comm_rank
     MPI_Comm_size
     MPI_Get_.*(?<!accumulate)
+    MPI_Win_(lock|unlock)
```
Comment (PhilMiller) [inline src/vt/pmpi/generate_mpi_wrappers.pl:130]: Can't `MPI_Win_lock` block on remote communication? That seems like exactly the sort of call that needs to be guarded.

**Comment by lifflander** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones removed
==============
+ src/vt/messaging/active.cc  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/lifflander/vt/pullRequest?prid=6334599&bid=20579140)

**Comment by lifflander** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones removed
==============
+ src/vt/messaging/active.cc  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/lifflander/vt/pullRequest?prid=6334599&bid=20579140)

**Comment by lifflander** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones removed
==============
+ src/vt/messaging/active.cc  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/lifflander/vt/pullRequest?prid=6334599&bid=20579140)

**Comment by lifflander** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones removed
==============
+ src/vt/messaging/active.cc  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/lifflander/vt/pullRequest?prid=6334599&bid=20579140)

File: src/vt/messaging/active.cc [hunk 5]
```diff
@@ -469,20 +540,87 @@ ActiveMessenger::SendDataRetType ActiveMessenger::sendData(
     l->send(dest, num_bytes, false);
   }
 
-  return SendDataRetType{event_id,send_tag};
+  return SendInfo{event_id, send_tag, num};
+}
+
+std::tuple<EventType, int> ActiveMessenger::sendDataMPI(
+  RDMA_GetType const& payload, NodeType const& dest, TagType const& tag
```
Comment (PhilMiller) [inline src/vt/messaging/active.cc:547]: Still not a fan of the types here having RDMA in their name. Nor of the use of `get` versus named members or accessors

File: src/vt/messaging/active.cc [hunk 6]
```diff
@@ -469,20 +540,87 @@ ActiveMessenger::SendDataRetType ActiveMessenger::sendData(
...
+    num_sends++;
+    events.push_back(event_id);
+  }
+
+  if (events.size() > 1) {
+    ret_event = theEvent()->createParentEvent(theContext()->getNode());
+    auto& holder = theEvent()->getEventHolder(ret_event);
+    for (auto&& child_event : events) {
+      holder.get_event()->addEventToList(child_event);
+    }
```
Comment (PhilMiller) [inline src/vt/messaging/active.cc:603]: This block seems a bit awkward, but it's inconsequential

File: src/vt/messaging/active.cc [hunk 7]
```diff
@@ -491,8 +629,8 @@ bool ActiveMessenger::tryProcessDataMsgRecv() {
 
   for (; iter != pending_recvs_.end(); ++iter) {
     auto const done = recvDataMsgBuffer(
-      iter->second.user_buf, iter->second.priority, iter->first,
-      iter->second.recv_node, false, iter->second.dealloc_user_buf,
+      iter->second.nchunks, iter->second.user_buf, iter->second.priority,
+      iter->first, iter->second.sender, false, iter->second.dealloc_user_buf,
```
Comment (PhilMiller) [inline src/vt/messaging/active.cc:633]: Could you name `auto& foo = iter->second`?

File: src/vt/messaging/active.cc [hunk 8]
```diff
@@ -611,21 +704,100 @@ bool ActiveMessenger::recvDataMsgBuffer(
...
+) {
+  vtAssert(nchunks > 0, "Must have at least one chunk");
+
+  std::vector<MPI_Request> reqs;
+  reqs.resize(nchunks);
+
+  char* cbuf = static_cast<char*>(buf);
+  MsgSizeType remainder = len;
+  for (int i = 0; i < nchunks; i++) {
+    auto const max_per_send = theConfig()->vt_max_mpi_send_size;
```
Comment (PhilMiller) [inline src/vt/messaging/active.cc:750]: This can be lifted out of the loop

**Comment by PhilMiller** [comment]
Reading on my phone, so I can't get a great overview at the moment. I think we're close on this

File: src/vt/messaging/active.cc (hunk 7 above)
Comment (lifflander) [reply src/vt/messaging/active.cc:633]: Done

File: src/vt/messaging/active.cc (hunk 8 above)
Comment (lifflander) [reply src/vt/messaging/active.cc:750]: Done

File: src/vt/messaging/active.cc (hunk 5 above)
Comment (lifflander) [reply src/vt/messaging/active.cc:547]: Ok, I've done this refactoring

**Comment by lifflander** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones removed
==============
+ src/vt/messaging/active.cc  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/lifflander/vt/pullRequest?prid=6334599&bid=20579140)

File: src/vt/configs/arguments/args.cc [hunk 9]
```diff
@@ -485,6 +485,18 @@ void ArgConfig::addConfigFileArgs(CLI::App& app) {
   a2->group(configGroup);
 }
 
+void ArgConfig::addRuntimeArgs(CLI::App& app) {
```
Comment (PhilMiller) [inline src/vt/configs/arguments/args.cc:488]: Not a problem, but why is this 'RuntimeArgs' instead of 'MessengerArgs'?

File: src/vt/messaging/active.cc [hunk 10]
```diff
@@ -248,6 +248,124 @@ EventType ActiveMessenger::sendMsgBytesWithPut(
...
+  } else {
+    vt_debug_print(
+      active, node,
+      "sendMsgMPI: (multi): size={}\n", msg_size
+    );
+    auto tag = allocateNewTag();
+    auto this_node = theContext()->getNode();
+
+    PtrLenPairType tup = std::make_tuple(untyped_msg, msg_size);
+    SendInfo info = sendData(tup, dest, tag);
```
Comment (PhilMiller) [inline src/vt/messaging/active.cc:356]: This is a very minor point, but every time I've read over this block, I've struggled to visually pick out where the "send the multiple chunks of data" call is. Perhaps a blank line here, after `sendData`, would make it at least slightly more distinguishable

File: src/vt/messaging/active.cc [hunk 11]
```diff
@@ -469,31 +540,98 @@ ActiveMessenger::SendDataRetType ActiveMessenger::sendData(
...
+  auto const max_per_send = theConfig()->vt_max_mpi_send_size;
+  while (remainder > 0) {
+    auto const event_id = theEvent()->createMPIEvent(this_node_);
+    auto& holder = theEvent()->getEventHolder(event_id);
+    auto mpi_event = holder.get_event();
+    auto subsize = static_cast<ByteType>(
+      std::min(static_cast<std::size_t>(remainder), max_per_send)
+    );
+    {
+      VT_ALLOW_MPI_CALLS;
```
Comment (PhilMiller) [inline src/vt/messaging/active.cc:563]: If we're going to wrap a block around `VT_ALLOW_MPI_CALLS`, could we do it tightly around the call itself? Having all of the tracing, debug prints, etc inside this extra block is confusin, relative to the `while` loop

**Comment by PhilMiller** [comment]
At least some of the failing tests are quite real - there's a memory leak reported of an allocation in `recvDataDirect`. I don't immediately see it in the code, but that needs to be hunted down.

**Comment by lifflander** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones removed
==============
+ src/vt/messaging/active.cc  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/lifflander/vt/pullRequest?prid=6334599&bid=20579140)

**Comment by lifflander** [comment]
> At least some of the failing tests are quite real - there's a memory leak reported of an allocation in `recvDataDirect`. I don't immediately see it in the code, but that needs to be hunted down.

I think I have the final fixes in place to get it ASAN clean.

**Comment by lifflander** [comment]
Looks like the OpenMPI failure is real also:

```
       Start 167: vt:*TestRDMAHandleCollection/*test_rdma_handle_collection_1_proc_2
4689
167/267 Test #167: vt:*TestRDMAHandleCollection/*test_rdma_handle_collection_1_proc_2 .................***Timeout  60.00 sec
4690
Note: Google Test filter = *TestRDMAHandleCollection/*test_rdma_handle_collection_1
4691
[==========] Running 2 tests from 2 test suites.
4692
[----------] Global test environment set-up.
4693
[----------] 1 test from test_rdma_handle_collection/TestRDMAHandleCollection/0, where TypeParam = int
4694
[ RUN      ] test_rdma_handle_collection/TestRDMAHandleCollection/0.test_rdma_handle_collection_1
4695
Note: Google Test filter = *TestRDMAHandleCollection/*test_rdma_handle_collection_1
4696
[==========] Running 2 tests from 2 test suites.
4697
[----------] Global test environment set-up.
4698
[----------] 1 test from test_rdma_handle_collection/TestRDMAHandleCollection/0, where TypeParam = int
4699
[ RUN      ] test_rdma_handle_collection/TestRDMAHandleCollection/0.test_rdma_handle_collection_1
4700
vt: Runtime Initializing: interop=true: mode: single-thread per rank
4701
vt: Program: rdma_extended (./rdma_extended)
4702
vt: Running on: 2 nodes
4703
vt: Machine Hostname: 5363ff24db98
4704
vt: MPI Version: 3.1
4705
vt: MPI Max tag: 2147483647
4706
vt: Build SHA: 2a8510588645044215b8d651aa3354e8e64253cc
4707
vt: Build Ref: 
4708
vt: Description: remotes/pull/1113/merge-0-g2a85105886 
4709
vt: Compile-time Features Enabled:
4710
vt: 	C++ Trait Detector
4711
vt: 	OpenMP Threading
4712
vt: 	Message priorities
4713
vt: 	Memory Pooling
4714
vt: 	MPI access guards
4715
vt: 	Performance analysis diagnostics
4716
vt: Runtime Configuration:
4717
vt: 	Option: flag --vt_sched_num_progress on: Running MPI progress 2 times each invocation
4718
vt: 	Option: flag --vt_sched_progress_han on: Running MPI progress function at least every 0 handler(s) executed
4719
vt: 	Option: flag --vt_print_no_progress on: Printing warnings when progress is stalls
4720
vt: 	Default: Printing verbose epoch graphs when hang detected, use --vt_epoch_graph_terse to disable
4721
vt: 	Option: flag --vt_epoch_graph_on_hang on: Epoch graph output enabled if hang detected
4722
vt: 	Default: Termination hang detection enabled by default, use --vt_no_detect_hang to disable
4723
vt: 	Option: flag --vt_hang_detect on: Printing stall warning every 1024 tree traversals 
4724
vt: 	Default: SIGINT signal handling enabled by default, use --vt_no_SIGINT to disable
4725
vt: 	Default: SIGSEGV signal handling enabled by default, use --vt_no_SIGSEGV to disable
4726
vt: 	Default: std::terminate signal handling enabled by default, use --vt_no_terminate to disable
4727
vt: 	Default: Color output enabled, use --vt_no_color to disable
4728
vt: 	Default: Stack dumps enabled by default, use --vt_no_stack to disable
4729
vt: 	Option: flag --vt_memory_reporters on: Memory usage checker precedence: mstats,machinfo,selfstat,selfstatm,sbrk,mallinfo,getrusage,ps
4730
vt: 	Working memory reporters: selfstatm,mallinfo,getrusage
4731
vt: 	Initial memory usage: selfstatm=16.8008 mallinfo=1.56895 getrusage=16.8008 (MiB)
4732
vt: 	Default: Memory usage printing disabled, use --vt_print_memory_each_phase to enable
4733
vt: 	Default: Diagnostics are disabled by default, use --vt_diag_enable to enable
4734
vt: 	Option: flag --vt_max_mpi_send_size on: Splitting messages greater than 1.0 GiB
4735
vt: Pass-through Arguments:
4736
vt: 	None. All arguments handled.
4737
[5363ff24db98:03794] Read -1, expected 8, errno = 1
4738
[5363ff24db98:03793] Read -1, expected 8, errno = 1
4739
[5363ff24db98:03793] Read -1, expected 8, errno = 1
4740
[5363ff24db98:03793] Read -1, expected 8, errno = 1
4741
[5363ff24db98:03793] Read -1, expected 8, errno = 1
4742
[5363ff24db98:03793] Read -1, expected 8, errno = 1
4743
[5363ff24db98:03793] Read -1, expected 8, errno = 1
4744
[5363ff24db98:03793] Read -1, expected 8, errno = 1
4745
[5363ff24db98:03793] Read -1, expected 8, errno = 1
4746
[5363ff24db98:03793] Read -1, expected 8, errno = 1
4747
[5363ff24db98:03793] Read -1, expected 8, errno = 1
4748
[5363ff24db98:03793] Read -1, expected 8, errno = 1
4749
[5363ff24db98:03793] Read -1, expected 8, errno = 1
4750
[5363ff24db98:03793] Read -1, expected 8, errno = 1
4751
[5363ff24db98:03793] Read -1, expected 8, errno = 1
4752
[5363ff24db98:03793] Read -1, expected 8, errno = 1
4753
[5363ff24db98:03793] Read -1, expected 8, errno = 1
4754
[5363ff24db98:03793] Read -1, expected 8, errno = 1
4755
[5363ff24db98:03793] Read -1, expected 8, errno = 1
4756
[5363ff24db98:03793] Read -1, expected 8, errno = 1
4757
[5363ff24db98:03793] Read -1, expected 8, errno = 1
4758
[5363ff24db98:03793] Read -1, expected 8, errno = 1
4759
[5363ff24db98:03793] Read -1, expected 8, errno = 1
4760
[5363ff24db98:03793] Read -1, expected 8, errno = 1
4761
[5363ff24db98:03793] Read -1, expected 8, errno = 1
4762
[5363ff24db98:03793] Read -1, expected 8, errno = 1
4763
[5363ff24db98:03793] Read -1, expected 8, errno = 1
4764
[5363ff24db98:03793] Read -1, expected 8, errno = 1
4765
[5363ff24db98:03793] Read -1, expected 8, errno = 1
4766
[5363ff24db98:03793] Read -1, expected 8, errno = 1
4767
[5363ff24db98:03793] Read -1, expected 8, errno = 1
4768
[5363ff24db98:03793] Read -1, expected 8, errno = 1
4769
[5363ff24db98:03793] Read -1, expected 8, errno = 1
4770
[5363ff24db98:03793] Read -1, expected 8, errno = 1
4771
[5363ff24db98:03793] Read -1, expected 8, errno = 1
4772
[5363ff24db98:03793] Read -1, expected 8, errno = 1
4773
[5363ff24db98:03793] Read -1, expected 8, errno = 1
4774
[5363ff24db98:03793] Read -1, expected 8, errno = 1
4775
[5363ff24db98:03793] Read -1, expected 8, errno = 1
```
Something with RDMA goes wrong.

File: src/vt/configs/arguments/args.cc (hunk 9 above)
Comment (lifflander) [reply src/vt/configs/arguments/args.cc:488]: Could be either. I just happened to choose that one.

File: src/vt/messaging/active.cc (hunk 10 above)
Comment (lifflander) [reply src/vt/messaging/active.cc:356]: I've added some comments and better spacing.

File: src/vt/messaging/active.cc (hunk 11 above)
Comment (lifflander) [reply src/vt/messaging/active.cc:563]: Done

**Review by PhilMiller — APPROVED** [review]

**Review by cz4rs — APPROVED** [review]
