### PR TITLE
794 Fix signal holder cleanup bug

### LINKED ISSUE #794: Callback IDs reset but signal holder not cleared
**Describe the bug**
When VT finalizes, it resets the callback IDs. However, the signal holder that holds the set of functions to invoke on a CB, doesn't get cleared because it's static data.

I killed an hour trying to figure why a callback was being invoked multiple times when running gtests.

Need to register cleanup lambdas for these to probably refactor callback re-use after the signals are triggered.

### PR DESCRIPTION
**Pull request by lifflander**
Fixes #794 

Fixes a bug discovered when writing safe MPI collective code. If the VT runtime is finalized, the pipe IDs are reset (used to identify a callback instance). But, the signal holder, which is a templated static container are not reset. Thus, the old registered listeners get triggered causing all sort of havoc. This was especially disturbing with testing, but many gtest tests run multiple tests in the same harness instance in one execution finalizing the VT runtime in between tests.

This also indicates that we probably need to audit all static (especially templated) data that is used in the runtime. There may be other static/global instances that would cause problems across finalizations or if VT is initialized twice (only halfway supported).

### CODE REVIEW

**Comment by lifflander** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- tests/unit/pipe/test_signal_cleanup.cc  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/lifflander/vt/pullRequest?prid=5684926&bid=18607398)

**Comment by lifflander** [comment]
@PhilMiller @pnstickne Can you review this?

File: src/vt/pipe/signal/signal_holder.cc [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+//
+// Questions? Contact darma@sandia.gov
+//
+// *****************************************************************************
+//@HEADER
+*/
+
+namespace vt { namespace pipe { namespace signal {
+
+/*static*/ int signal_holder_next_id_ = 1;
```
Comment (pnstickne) [inline src/vt/pipe/signal/signal_holder.cc:47]: `unsigned`?

File: src/vt/pipe/pipe_manager_base.impl.h [hunk 2]
```diff
@@ -111,11 +111,21 @@ template <typename SignalT, typename ListenerT>
 void PipeManagerBase::registerCallback(
   PipeType const& pipe, ListenerT&& listener, bool update_state
 ) {
+  auto& holder = signal_holder_<SignalT>;
```
Comment (pnstickne) [inline src/vt/pipe/pipe_manager_base.impl.h:114]: If high variance of ListenerT, put in function templated only on SignalT only. (It really helps out Clang's template over lambdas.)

File: src/vt/pipe/pipe_manager_base.impl.h [hunk 3]
```diff
@@ -111,11 +111,21 @@ template <typename SignalT, typename ListenerT>
...
+      signal_holder_<SignalT>.clearAll();
+    };
+  }
+
   /*
    *  Save the new listener in the typed signal holder container for delivery
    *  when a signal arrives
    */
-  signal_holder_<SignalT>.addListener(pipe,std::move(listener));
+  holder.addListener(pipe,std::move(listener));
```
Comment (pnstickne) [inline src/vt/pipe/pipe_manager_base.impl.h:128]: Missing space.

File: src/vt/pipe/signal/signal_holder.h [hunk 4]
```diff
@@ -74,6 +78,10 @@ struct SignalHolder {
   using CountMapType         = std::unordered_map<PipeType,SigCountType>;
   using ListenerMapIterType  = typename ListenerMapType::iterator;
 
+  SignalHolder()
```
Comment (pnstickne) [inline src/vt/pipe/signal/signal_holder.h:81]: Could move some to cc.

File: src/vt/pipe/pipe_manager_base.h [hunk 5]
```diff
@@ -161,6 +163,8 @@ struct PipeManagerBase {
   PipeIDType cur_pipe_id_ = initial_pipe_id;
   // the pipe state for pipes that have a send back
   std::unordered_map<PipeType,PipeStateType> pipe_state_;
+  // ID -> type-erased SignalHolder<T> cleanup lambda
+  std::unordered_map<int, std::function<void()>> signal_cleanup_fns_;
```
Comment (pnstickne) [inline src/vt/pipe/pipe_manager_base.h:167]: Are number of ID's bound? Does it make sense to perform cleanup prior to destructor?

File: src/vt/pipe/pipe_manager_base.impl.h [hunk 6]
```diff
@@ -111,11 +111,21 @@ template <typename SignalT, typename ListenerT>
 void PipeManagerBase::registerCallback(
   PipeType const& pipe, ListenerT&& listener, bool update_state
 ) {
+  auto& holder = signal_holder_<SignalT>;
+  auto const holder_id = holder.getID();
+
+  auto cleanup_iter = signal_cleanup_fns_.find(holder_id);
+  if (cleanup_iter == signal_cleanup_fns_.end()) {
+    signal_cleanup_fns_[holder_id] = []{
+      signal_holder_<SignalT>.clearAll();
```
Comment (pnstickne) [inline src/vt/pipe/pipe_manager_base.impl.h:120]: Can there be multiple IDs per holder? Seems suspect if so as clearAll is all..

Comment (pnstickne) [reply src/vt/pipe/pipe_manager_base.impl.h:120]: Disregard.. late night.

File: src/vt/pipe/pipe_manager_base.impl.h (hunk 2 above)
Comment (lifflander) [reply src/vt/pipe/pipe_manager_base.impl.h:114]: Will consider for the future

**Comment by lifflander** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- tests/unit/pipe/test_signal_cleanup.cc  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/lifflander/vt/pullRequest?prid=5684926&bid=18607398)
