### PR TITLE
1913 Add option of headerless pool

### LINKED ISSUE #1913: Add option to optimize memory pool when a header is not needed
**Describe the bug**

**To Reproduce**
1. Example/test/snippet of code that fails
2. Compiler, platform, libraries
3. Run command: number of processors, threading options, etc.

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - Supercomputer or desktop [e.g., Trinity, Sierra)
 - Compiler environment [e.g., clang-3.9, gcc8]
 - Libraries [e.g., mpich-2, openmpi)
 - Commit ID or release of VT [e.g., vt-1.0.0]

**Additional context**

### PR DESCRIPTION
**Pull request by stmcgovern**
Closes #1913.

### CODE REVIEW

**Comment by PhilMiller** [comment]
This more more a request of Jonathan than Sean: Could you document in the code when a header would or wouldn't be necessary/useful?

File: src/vt/pool/static_sized/memory_pool_equal.cc [hunk 1]
```diff
@@ -52,8 +52,9 @@
 namespace vt { namespace pool {
 
 template <int64_t num_bytes_t>
-MemoryPoolEqual<num_bytes_t>::MemoryPoolEqual(SlotType const in_pool_size)
-  : pool_size_(in_pool_size)
+MemoryPoolEqual<num_bytes_t>::MemoryPoolEqual(SlotType const in_pool_size, bool in_use_header)
```
Comment (PhilMiller) [inline src/vt/pool/static_sized/memory_pool_equal.cc:55]: Possibly as comments on the parameters here?

It would also be useful to document whether `in_poll_size` is in units of bytes or objects of size `num_bytes_t` or something else

**Review by PhilMiller — CHANGES_REQUESTED** [review]
Per discussion in today's meeting, this should pull in the later changes to make `use_header` a template parameter, rather than a runtime parameter

**Review by PhilMiller — APPROVED** [review]
