### PR TITLE
1094 Fix collective scope de-allocation

### LINKED ISSUE #1094: Collective scopes are not de-allocated after use
**Describe the bug**
`CollectiveScope` is leaking memory even when it goes out of scope.

### PR DESCRIPTION
**Pull request by lifflander**
Fixes #1094

- There's a race between the de-allocation of a scope (when it goes out of scope) and the completion of the work. If the work completes before it goes out of scope it doesn't erase
- There's a bug in the scope when it's moved causing double de-allocation if it goes out of scope before completion of work
- Add tests that expose these bugs and then fix them

### CODE REVIEW

**Comment by lifflander** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- tests/unit/collectives/test_mpi_collective.cc  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/lifflander/vt/pullRequest?prid=6249502&bid=20351562)

File: tests/unit/collectives/test_mpi_collective.cc [hunk 1]
```diff
@@ -232,4 +261,34 @@ TEST_F(TestMPICollective, test_mpi_collective_4) {
...
+
+  {
+    vt::collective::CollectiveScope scope = theCollective()->makeCollectiveScope();
+    vt::collective::CollectiveScope scope2{std::move(scope)};
+
+    is_user_scope = scope2.isUserTag();
+    scope_bits = scope2.getScopeBits();
+
+    // These three collective can execute in any order, but it will always be
+    // consistent across all the nodes
```
Comment (nlslatt) [inline tests/unit/collectives/test_mpi_collective.cc:279]: Is this comment relevant here?

**Comment by lifflander** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- tests/unit/collectives/test_mpi_collective.cc  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/lifflander/vt/pullRequest?prid=6249502&bid=20351562)

File: tests/unit/collectives/test_mpi_collective.cc (hunk 1 above)
Comment (lifflander) [reply tests/unit/collectives/test_mpi_collective.cc]: Removed

**Review by pnstickne — APPROVED** [review]
