### PR TITLE
#2390: getRecentTime() should not be used when tracing is enabled

### LINKED ISSUE #2390: getRecentTime() should not be used when tracing is enabled
**Describe the bug**
In runnable.cc, using the "recent time" to avoid calling the timer which is expensive leads to highly inaccurate traces. We should get the current time when tracing is compile-time enabled and being used at runtime (i.e., the trace context is enabled for a runnable).

### PR DESCRIPTION
**Pull request by cwschilly**
Fixes #2390

### CODE REVIEW

File: src/vt/runnable/runnable.cc [hunk 1]
```diff
@@ -124,7 +124,16 @@ void RunnableNew::run() {
...
     needs_time = contexts_.lb.needsTime();
   }
-  TimeType start_time = needs_time ? theSched()->getRecentTime() : TimeType{NAN};
+
+  auto getTime = [&]() {
+#if vt_check_enabled(trace_enabled)
+    if (theTrace()) return timing::getCurrentTime();
+    else
+#endif
+    return theSched()->getRecentTime();
```
Comment (PhilMiller) [inline src/vt/runnable/runnable.cc:133]:
```suggestion
    {
      return theSched()->getRecentTime();
    }
```
Makes it more clear that there's a control flow statement preceding it.

This also better matches the style adopted for conditionally-compiled conditions.

Comment (cwschilly) [reply src/vt/runnable/runnable.cc]: Fixed, thanks

**Review by cz4rs — APPROVED** [review]

**Review by lifflander — APPROVED** [review]
