### PR TITLE
1260: Fix active messaging functor inference using the FunctorExtractor

### LINKED ISSUE #1260: Active messaging functor inference using the FunctorExtractor is broken?
**Describe the bug**
Sending a message to a functor with the `ActiveMessenger` requires the message type, which should be inferred. This might be related to changes to the message thief.

Write a test that replicates this problem and solve it.

### PR DESCRIPTION
**Pull request by JacobDomagala**
Fixes #1260

### CODE REVIEW

File: tutorial/tutorial_1b.h [hunk 1]
```diff
@@ -154,7 +154,7 @@ static void msgHandlerA(MyMsg* msg) {
   NodeType const to_node = 0;
   auto msg2 = ::vt::makeMessage<MyMsg>(10,20);
 
-  ::vt::theMsg()->sendMsg<MsgHandlerB, MyMsg>(to_node, msg2);
+  ::vt::theMsg()->sendMsg<MsgHandlerB>(to_node, msg2);
```
Comment (JacobDomagala) [inline tutorial/tutorial_1b.h:157]: This reproduces the issue

Comment (JacobDomagala) [reply tutorial/tutorial_1b.h:157]: Also as a more isolated example https://cppinsights.io/s/0a6836aa.

File: src/vt/messaging/active.h [hunk 2]
```diff
@@ -904,7 +904,7 @@ struct ActiveMessenger : runtime::component::PollableComponent<ActiveMessenger>
     typename MsgT = typename util::FunctorExtractor<FunctorT>::MessageType
   >
   PendingSendType broadcastMsg(
-    MsgPtrThief<MsgT> msg,
+    MsgPtrThief<typename util::FunctorExtractor<FunctorT>::MessageType> msg,
```
Comment (JacobDomagala) [inline src/vt/messaging/active.h:907]: This ugly fix makes MsgT not needed anymore. For vt's sake we could remove it from the interface but I can assume either EMPIRE or NimbleSM could be using send/braodcast with both explicit template arguments.

File: CMakeLists.txt [hunk 3]
```diff
@@ -101,9 +101,9 @@ option(vt_werror_enabled "Build VT with -Werror enabled" OFF)
 if (vt_werror_enabled)
   enable_cxx_compiler_flag_if_supported("-Werror")
 endif()
-include(cmake/load_bundled_libraries.cmake)
 
 include(cmake/nvcc_no_deprecated_gpu_targets.cmake)
+include(cmake/load_bundled_libraries.cmake)
```
Comment (jstrzebonski) [inline CMakeLists.txt:106]: Nice

File: src/vt/messaging/active.h (hunk 2 above)
Comment (PhilMiller) [reply src/vt/messaging/active.h:907]: Considering this in isolation, I think it might be worthwhile to take that breaking change. It actually partially addresses the goal of #276, of not having to type the message type at every send call site.

Comment (PhilMiller) [reply src/vt/messaging/active.h:907]: Removing it from the interface may not be worth much, though, since it won't actually change the number of template instantiations at all.

**Comment by PhilMiller** [comment]
I *really* like what this does. I want to request an extension to cover updating the codebase as broadly as possible, but that's asking for merge conflicts. Let's get this integrated, and then clean things up across the board in a follow-on PR.

File: src/vt/messaging/active.h (hunk 2 above)
Comment (PhilMiller) [reply src/vt/messaging/active.h:907]: It may make sense in all of these methods to have something along the lines of 

`static_assert(std::is_same<MsgT, typename util::FunctorExtractor<FunctorT>::MessageType>::value, "Message type must match type of handler argument");`

so that mixups get caught

**Comment by PhilMiller** [comment]
Could the same thing be done to the interfaces on objgroup and collection proxies?

**Comment by JacobDomagala** [comment]
This PR is merely just a bugfix for Active send/broadcast when used with Functor handler. For any arbitrary handler we're limited by C++14's lack of using the object as template argument, without specifying its type first. 

If we really would want to get rid of explicit message type, I think the best we can do currently is:
```c++
template <typename HandlerType, HandlerType handler>
send(MsgPtrThief<typename FunctionExtractor<HandlerType >::MsgType >msg, ...)
```

Then we could provide helper macro like so:
```c++ 
#define VT_HANDLER(handler) decltype(&handler), &handler
```

which would make the call to `send` look like this:
```c++
send<VT_HANDLER(myHandler)>(my_msg);
```

Example: https://godbolt.org/z/fK6xvjWa8

**Review by lifflander — APPROVED** [review]
Look good

**Comment by JacobDomagala** [comment]
I just realized that this change enforces the user to have a Functor with only single `operator()` defined. Otherwise it won't compile. I think I will have to update this PR

File: examples/hello_world/hello_world_functor.cc [hunk 4]
```diff
@@ -70,7 +82,21 @@ int main(int argc, char** argv) {
 
   if (this_node == 0) {
     auto msg = vt::makeMessage<HelloMsg>(this_node);
-    vt::theMsg()->broadcastMsg<HelloWorld,HelloMsg>(msg);
+
+    // 'HelloWorld' functor has only single 'operator()' declared
+    // so we can call send/braodcast without specyfing message type
```
Comment (PhilMiller) [inline examples/hello_world/hello_world_functor.cc:87]: Typo here 'specifying'

Comment (PhilMiller) [reply examples/hello_world/hello_world_functor.cc:87]: And 'broadcast'

File: examples/hello_world/hello_world_functor.cc [hunk 5]
```diff
@@ -70,7 +82,21 @@ int main(int argc, char** argv) {
...
+    msg = vt::makeMessage<HelloMsg>(this_node);
+    vt::theMsg()->sendMsg<HelloWorld>(1, msg);
+
+    // 'MultipleFunctions' functor declares more than one 'operator()'
+    // so we have to specify the type of the message, as it can't be deduced
+    auto new_msg = vt::makeMessage<AnotherMsg>();
+    vt::theMsg()->broadcastMsg<MultipleFunctions, AnotherMsg>(new_msg);
+
+    new_msg = vt::makeMessage<AnotherMsg>();
+    vt::theMsg()->sendMsg<MultipleFunctions, AnotherMsg>(1, new_msg);
```
Comment (PhilMiller) [inline examples/hello_world/hello_world_functor.cc:99]: Is one of these intended to send `HelloMsg` to illustrate use of both overloads of `MultupleFunctions::operator()`?

File: src/vt/utils/static_checks/functor.h [hunk 6]
```diff
@@ -47,6 +47,7 @@
 
 #include "vt/config.h"
 
+
```
Comment (PhilMiller) [inline src/vt/utils/static_checks/functor.h:50]: Stray newline added here

File: examples/hello_world/hello_world_functor.cc (hunk 5 above)
Comment (JacobDomagala) [reply examples/hello_world/hello_world_functor.cc]: Wasn't intended, but I think it's actually good idea to add it.

**Review by PhilMiller — APPROVED** [review]
